/* 李承霖大王的光学复习 · 选择题真题题库
 * 内容来源：电子科技大学 840 物理光学考研真题（2008~2024）的选择题部分，
 * 题干与选项从扫描件逐题转录，答案取自配套的《真题答案解析》。
 * a 是正确选项下标（0 = A）；null 表示答案册没给字母（只有 2011 年第 8 题，
 * 答案册记作 A、D 两说）。
 * 2018 / 2021 两年卷面本身没有选择题；2019 的 5 题、2020 的 1 题、2022 的第 7 题、
 * 2023 的第 12/18/15 题因卷面缺选项或不是四选一，未收录。
 * 图在 assets/mc/ 下；题干里的 <span class="blank"></span> 是原卷的填空下划线。
 *
 * 本文件由 /tmp/po_extract/mc/build.py 生成，不要手改。
 */
var MC_YEARS = [
  { id: 2008, title: "真题选择题", sub: "840 物理光学", n: 20, note: "选择题 20 题，每题 3 分，共 60 分。" },
  { id: 2009, title: "真题选择题", sub: "840 物理光学", n: 20, note: "选择题 20 题，每题 3 分，共 60 分。" },
  { id: 2010, title: "真题选择题", sub: "840 物理光学", n: 21, note: "选择题 21 题，每题 3 分，共 63 分。" },
  { id: 2011, title: "真题选择题", sub: "840 物理光学", n: 20, note: "选择题 20 题，每题 3 分。第 8 题答案册给了 A、D 两种说法，本题不计对错。" },
  { id: 2012, title: "真题选择题", sub: "840 物理光学", n: 24, note: "选择题 25 题，每题 2 分。第 25 题卷面是填空题、没有印选项，未收录，实收 24 题。" },
  { id: 2013, title: "真题选择题", sub: "840 物理光学", n: 25, note: "选择题 25 题，每题 2 分。" },
  { id: 2014, title: "真题选择题", sub: "840 物理光学", n: 25, note: "选择题 25 题，每题 2 分。" },
  { id: 2015, title: "真题选择题", sub: "840 物理光学", n: 20, note: "选择题 20 题，每题 3 分。" },
  { id: 2016, title: "真题选择题", sub: "840 物理光学", n: 25, note: "选择题 25 题，每题 2 分。" },
  { id: 2017, title: "真题选择题", sub: "840 物理光学", n: 33, note: "回忆版，共 33 题。原卷选择题按章编排、每章题号各自从 1 开始，这里拉通编号：第 1~4 题是第 1 章，5~12 题第 2 章，13~22 题第 3 章，23~30 题第 4 章，31~33 题第 5 章。卷面注明这些是考点示例、并非当年原题。" },
  { id: 2022, title: "真题选择题", sub: "840 物理光学", n: 8, note: "回忆版，原卷 9 题。第 7 题只有一句题干、没有印选项，未收录，实收 8 题。本卷选项数不统一，第 1、4、5 题只有 3 个选项。" },
  { id: 2023, title: "真题选择题", sub: "840 物理光学", n: 17, note: "回忆版。原卷标「2 分 × 21」，但题号从 12 直接跳到 14（没有第 13 题），且第 12、18 题只有题干没有选项、第 15 题只印出 D 一个选项，这三题未收录，实收 17 题。" },
];

var MC = [
  { id: "m2008-1", y: 2008, num: 1,
    q: "以 <span class=\"m\">E</span><sub>s</sub>、<span class=\"m\">H</span><sub>s</sub> 分别表示光波垂直于入射面方向的电场分量和磁场分量，|<span class=\"m\">E</span><sub>s</sub>| 极大时，|<span class=\"m\">H</span><sub>s</sub>| <span class=\"blank\"></span>。",
    o: ["极大", "极小", "等于常数", "不确定"],
    a: 3,
  },
  { id: "m2008-2", y: 2008, num: 2,
    q: "某种透明媒质对于空气的临界角（指全反射）等于 45°，光从空气射向此媒质时的布儒斯特角是<span class=\"blank\"></span>度。",
    o: ["小于 45", "30", "45", "大于 45"],
    a: 3,
  },
  { id: "m2008-3", y: 2008, num: 3,
    q: "在 <span class=\"m\">n</span><sub>1</sub>/<span class=\"m\">n</span><sub>2</sub>/<span class=\"m\">n</span><sub>1</sub> 对称平板双光束干涉中，无论是等厚干涉还是等倾干涉，也无论是 <span class=\"m\">n</span><sub>1</sub> > <span class=\"m\">n</span><sub>2</sub> 还是 <span class=\"m\">n</span><sub>1</sub> < <span class=\"m\">n</span><sub>2</sub>，两光束的相对（反射）相位跳变总是<span class=\"blank\"></span>。",
    o: ["等于 π", "等于 0", "可以为 π 也可以为 0", "∈ [0, π]"],
    a: 0,
  },
  { id: "m2008-4", y: 2008, num: 4,
    q: "白炽光经单缝衍射，衍射条纹中有一条不呈现彩色，该条纹为<span class=\"blank\"></span>级条纹。",
    o: ["0", "+1", "−1", "最高"],
    a: 0,
  },
  { id: "m2008-5", y: 2008, num: 5,
    q: "费涅耳圆屏衍射中，如果圆屏直径有限大，则其中垂线上考察点 <span class=\"m\">P</span><span class=\"blank\"></span>。",
    o: ["总呈暗斑", "总呈亮斑", "可亮也可能暗", "时暗时亮"],
    a: 1,
  },
  { id: "m2008-6", y: 2008, num: 6,
    q: "一种偏振态的光可能有<span class=\"blank\"></span>种形式的偏振矩阵。",
    o: ["1", "2", "3", "多"],
    a: 3,
  },
  { id: "m2008-7", y: 2008, num: 7,
    q: "光栅面在铅垂面内，激光束经光栅衍射，在水平方向形成一簇衍射光斑，光栅的刻线方向与水平方向成夹角<span class=\"blank\"></span>。",
    o: ["<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">2</span></span>", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">4</span></span>", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">3</span></span>", "0"],
    a: 0,
  },
  { id: "m2008-8", y: 2008, num: 8,
    q: "晴朗的天空呈蓝色，是由于大气对日光的<span class=\"blank\"></span>。",
    o: ["反射", "衍射", "色散", "散射"],
    a: 3,
  },
  { id: "m2008-9", y: 2008, num: 9,
    q: "普通窗户玻璃对可见光的吸收属<span class=\"blank\"></span>。",
    o: ["选择吸收", "一般吸收", "强烈吸收", "双光子吸收"],
    a: 1,
  },
  { id: "m2008-10", y: 2008, num: 10,
    q: "入射光的谱线宽度 Δλ=0.1 μm，中心波长为 0.55 μm，设液膜的介质折射率 <span class=\"m\">n</span>=1.5，垂直入射时，能观察到液膜呈现的彩色等厚干涉图样，由此可以断定液膜可能的最大厚度约为<span class=\"blank\"></span> μm。",
    o: ["1", "2", "3", "4"],
    a: 0,  note: "原卷把谱线宽度印作 Δλ=0.1 μm（单位疑有误），此处照原卷。",
  },
  { id: "m2008-11", y: 2008, num: 11,
    q: "沿 Z 方向传播的光波在 X、Y 方向上的空间频率 <span class=\"m\">f</span><sub>x</sub>、<span class=\"m\">f</span><sub>y</sub> <span class=\"blank\"></span>。",
    o: ["不相等", "都等于 0", "都趋于无穷大", "随空间变化"],
    a: 1,
  },
  { id: "m2008-12", y: 2008, num: 12,
    q: "菲涅尔波带片有<span class=\"blank\"></span>个焦点",
    o: ["1", "2", "3", "多"],
    a: 3,
  },
  { id: "m2008-13", y: 2008, num: 13,
    q: "对于单层光学薄膜，增透膜和增反膜的光学厚度<span class=\"blank\"></span>。",
    o: ["分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>"],
    a: 2,
  },
  { id: "m2008-14", y: 2008, num: 14,
    q: "如图，记观察散射光的方向与入射光的传播方向成角度 θ，如果 θ≠0、<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">2</span></span>、π，入射光为自然光，则观察到的散射光为<span class=\"blank\"></span>。",
    o: ["自然光", "偏振方向垂直于纸面的偏振光", "偏振方向平行于纸面的偏振光", "部分偏振光"],
    a: 3,
    fig: ["2008-14.png"],
  },
  { id: "m2008-15", y: 2008, num: 15,
    q: "等倾干涉的光源一般为<span class=\"blank\"></span>。",
    o: ["点光源", "扩展光源", "平行光束", "单色光源"],
    a: 1,
  },
  { id: "m2008-16", y: 2008, num: 16,
    q: "F-P 腔面反射率 <span class=\"m\">R</span> 增加时，其干涉图样中亮线的亮度<span class=\"blank\"></span>。",
    o: ["增加", "减弱", "不变", "趋于无穷大"],
    a: 2,
  },
  { id: "m2008-17", y: 2008, num: 17,
    q: "决定平行平板干涉属双光束干涉还是多光束干涉的关键因素是平板的 <span class=\"blank\"></span>。",
    o: ["平行度", "厚度", "反射率", "折射率"],
    a: 2,
  },
  { id: "m2008-18", y: 2008, num: 18,
    q: "在各向异性晶体中，<span class=\"m\">E</span> 和 <span class=\"m\">D</span> 的方向<span class=\"blank\"></span>。",
    o: ["一定不同", "一定相同", "互相垂直", "不一定相同"],
    a: 3,
  },
  { id: "m2008-19", y: 2008, num: 19,
    q: "刻画光源空间相干性的物理量是<span class=\"blank\"></span>。",
    o: ["相干长度", "相干时间", "相干面积", "光源面积"],
    a: 2,
  },
  { id: "m2008-20", y: 2008, num: 20,
    q: "在牛顿环中，有 A、B 两个级次的彩环，A 级彩环较宽，B 级彩环较窄，由此可以断定<span class=\"blank\"></span>。",
    o: ["A>B", "A<B", "A=B", "A+B=const"],
    a: 1,
  },
  { id: "m2009-1", y: 2009, num: 1,
    q: "如图 a 所示，一光学平板玻璃 A 与待测工件 B 之间形成空气劈尖，用波长 λ=632.8 nm（1nm = 10<sup>−9</sup>m）的单色光垂直照射，看到反射光的干涉条纹如图 b 所示，有些条纹弯曲部分的顶点恰好与其右边条纹的直线部分的切线相切，则工件的上表面缺陷是 <span class=\"blank\"></span> 。",
    o: ["不平处为凸起纹，最大高度为 632.8 nm", "不平处为凸起纹，最大高度为 316.4 nm", "不平处为凹槽，最大深度为 632.8 nm", "不平处为凹槽，最大深度为 316.4 nm"],
    a: 1,
    fig: ["2009-1.png"],
  },
  { id: "m2009-2", y: 2009, num: 2,
    q: "入射光波长差 Δλ=0.1 μm，平均波长为 0.55 μm，设液膜介质的折射率 <span class=\"m\">n</span>=1.3，垂直入射时，能观察到液膜呈现的彩色等厚干涉图样，由此可以断定液膜可能的最大厚度约为 <span class=\"blank\"></span> μm。",
    o: ["1", "1.2", "3", "2.3"],
    a: 1,  note: "原卷把波长差印作 Δλ=0.1 μm（单位疑有误），此处照原卷。",
  },
  { id: "m2009-3", y: 2009, num: 3,
    q: "在平行平板双光束干涉和多光束干涉中，通常应用的<span class=\"blank\"></span>。",
    o: ["分别是反射光和透射光", "分别是透射光和反射光", "都是反射光", "都是透射光"],
    a: 0,
  },
  { id: "m2009-4", y: 2009, num: 4,
    q: "F-P 腔两内腔面间的距离 <span class=\"m\">h</span> 增加时，其自由光谱范围 Δλ <span class=\"blank\"></span> 。",
    o: ["恒定不变", "增加", "下降", "=0"],
    a: 2,
  },
  { id: "m2009-5", y: 2009, num: 5,
    q: "芙琅和费衍射图样呈一簇椭圆，长轴在 Y 方向，短轴在 Z 方向，衍射屏的通光孔为 <span class=\"blank\"></span> 。",
    o: ["圆", "窄缝", "椭圆，其长轴在 Z 方向", "椭圆，其长轴在 Y 方向"],
    a: 2,
  },
  { id: "m2009-6", y: 2009, num: 6,
    q: "在闪耀光栅中，计槽面宽度为 <span class=\"m\">a</span>，刻槽周期为 <span class=\"m\">d</span>，为有效应用光能，一般设计 <span class=\"m\">d</span>/<span class=\"m\">a</span> 约为 <span class=\"blank\"></span> 。",
    o: ["4", "3", "2", "1"],
    a: 3,
  },
  { id: "m2009-7", y: 2009, num: 7,
    q: "一束波长为 514 nm 的平行单色光垂直入射到一单缝 AB 上，AC 垂直于 BC，装置如图，在屏幕 <span class=\"m\">P</span> 上形成衍射图样，如果 <span class=\"m\">P</span> 是中央亮纹一侧第 2 个暗纹所在的位置，则 BC 的长度为 <span class=\"blank\"></span> nm 。",
    o: ["514", "257", "1542", "1028"],
    a: 3,
    fig: ["2009-7.png"],
  },
  { id: "m2009-8", y: 2009, num: 8,
    q: "为提高显微镜的分辨能力，可以 <span class=\"blank\"></span> 。",
    o: ["增加波长", "减小波长", "减小物方折射率", "减小数值孔径"],
    a: 1,
  },
  { id: "m2009-9", y: 2009, num: 9,
    q: "在均匀平面波垂直入射的芙琅和费多缝衍射中，相邻缝在观察屏上同一点的衍射场 <span class=\"blank\"></span> 。",
    o: ["振幅、相位都相同", "振幅、相位都不相同", "振幅相同、相位不相同", "振幅不相同、相位相同"],
    a: 2,
  },
  { id: "m2009-10", y: 2009, num: 10,
    q: "用 Wollaston 棱镜将一束 He-Ne 激光分成强度相等的两束光，这两束光 <span class=\"blank\"></span> 。",
    o: ["相干", "不相干", "具相同的偏振方向", "具不同的颜色"],
    a: 1,
  },
  { id: "m2009-11", y: 2009, num: 11,
    q: "记单轴晶体的主折射率 <span class=\"m\">n</span><sub>x</sub> = <span class=\"m\">n</span><sub>y</sub> = <span class=\"m\">n</span><sub>o</sub>，<span class=\"m\">n</span><sub>z</sub> = <span class=\"m\">n</span><sub>e</sub>，自然光入射，光在该晶体中传播时，无论 <span class=\"m\">k</span> 沿什么方向，总有一束光波的折射率 <span class=\"blank\"></span> 。",
    o: ["= <span class=\"m\">n</span><sub>o</sub>", "= <span class=\"m\">n</span><sub>e</sub>", "> <span class=\"m\">n</span><sub>o</sub>", "< <span class=\"m\">n</span><sub>o</sub>"],
    a: 0,
  },
  { id: "m2009-12", y: 2009, num: 12,
    q: "一束自然光通过介质时发生散射，如果观察到的散射光为线偏振光，则观察方向与入射光束的传播方向肯定 <span class=\"blank\"></span> 。",
    o: ["相同", "相反", "相交成 <span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">4</span></span>", "垂直"],
    a: 3,
  },
  { id: "m2009-13", y: 2009, num: 13,
    q: "蓝天和白云对日光的散射 <span class=\"blank\"></span> 。",
    o: ["为瑞利散射", "分别为瑞利散射和米氏散射", "为米氏散射", "分别为米氏散射和瑞利散射"],
    a: 1,
  },
  { id: "m2009-14", y: 2009, num: 14,
    q: "光波在真空中传播，波矢方向如图所示，已知其电场的 S 分量垂直于纸面向外，相应磁场的方向一定 <span class=\"blank\"></span> 。",
    o: ["垂直于纸面向外", "垂直于纸面向内", "平行于纸面向上", "平行于纸面向下"],
    a: 3,  note: "原卷此处印作「电场的 S 分量」（图中标注为 E<sub>s</sub>），照原卷。",
    fig: ["2009-14.png"],
  },
  { id: "m2009-15", y: 2009, num: 15,
    q: "<span class=\"m\">E</span><sub>x</sub> 和 <span class=\"m\">E</span><sub>y</sub> 在真空中构成椭圆偏振光，其长短轴之比为 2:1，<span class=\"m\">E</span><sub>x</sub> 的圆频率为 ω 时，<span class=\"m\">E</span><sub>y</sub> 的圆频率为 <span class=\"blank\"></span> 。",
    o: ["ω", "2ω", "ω/2", "4ω"],
    a: 0,
  },
  { id: "m2009-16", y: 2009, num: 16,
    q: "光在 <span class=\"blank\"></span> 中传播时，将有可能分为 o 光和 e 光。",
    o: ["单轴晶体", "双轴晶体", "各向同性晶体", "单轴晶体和双轴晶体"],
    a: 0,
  },
  { id: "m2009-17", y: 2009, num: 17,
    q: "有尖劈形薄膜，如图所示，如果将正入射的光波改为 30° 角入射，尖劈右端厚度、尖劈形薄膜的折射率、入射光的波长等条件不变，则总的等厚干涉条纹数量将 <span class=\"blank\"></span> 。",
    o: ["增加", "减少", "不变", "不确定"],
    a: 1,
    fig: ["2009-17.png"],
  },
  { id: "m2009-18", y: 2009, num: 18,
    q: "在白光入射 F-P 腔形成的的干涉图样中，同一级圆环中相应于颜色从兰到红的空间位置是 <span class=\"blank\"></span> 。",
    o: ["由外到里", "由里到外", "不变", "随机变化"],
    a: 0,
  },
  { id: "m2009-19", y: 2009, num: 19,
    q: "下图所示为多缝衍射的强度分布，θ 为衍射角，<span class=\"m\">d</span> 为缝间距，λ 为入射光波长，<span class=\"m\">a</span> 为缝宽，由图可以断定，<span class=\"m\">d</span>/<span class=\"m\">a</span> 的数值等于 <span class=\"blank\"></span> 。",
    o: ["4", "5", "6", "7"],
    a: 1,
    fig: ["2009-19.png"],
  },
  { id: "m2009-20", y: 2009, num: 20,
    q: "用单轴晶体做成的波片改变入射光的偏振态，晶体的光轴方向与晶体中光波的波矢方向一般成 <span class=\"blank\"></span> 度角。",
    o: ["0", "0 或 90", "45", "90"],
    a: 3,
  },
  { id: "m2010-1", y: 2010, num: 1,
    q: "如图所示，两光学平板玻璃 A 与 B 之间形成空气劈尖，如果将劈尖的空气换成水，平行入射光有足够的相干长度，且入射光波长和入射角度等条件不变，则等厚干涉图样中总的条纹数量将 <span class=\"blank\"></span> 。",
    o: ["减少", "增加", "不变", "不确定"],
    a: 1,
    fig: ["2010-1.png"],
  },
  { id: "m2010-2", y: 2010, num: 2,
    q: "如右图所示，光束经偏振片 <span class=\"m\">P</span> 后测定其强度。如果当偏振片 <span class=\"m\">P</span> 旋转一周时，出射光强度 <span class=\"m\">I</span> 保持不变，则可以肯定入射光是 <span class=\"blank\"></span> 。",
    o: ["圆偏振光", "椭圆偏振光", "自然光", "自然光或圆偏振光"],
    a: 3,
    fig: ["2010-2.png"],
  },
  { id: "m2010-3", y: 2010, num: 3,
    q: "在下图所示的望远成像系统中，增加成像系统透镜 <span class=\"m\">L</span> 的焦距 <span class=\"m\">f</span>，从而可以在更远的平面上成像，进而使远处同样张角 α 的两点物 <span class=\"m\">S</span><sub>1</sub>、<span class=\"m\">S</span><sub>2</sub> 在像平面上的像 <span class=\"m\">S</span><sub>1</sub>′、<span class=\"m\">S</span><sub>2</sub>′ 的距离 <span class=\"m\">S</span><sub>1</sub>′<span class=\"m\">S</span><sub>2</sub>′ 更远，但孔径等其它参数、条件不变，成像系统的分辨本领 <span class=\"blank\"></span> 。",
    o: ["提高", "不变", "降低", "决定于点物的辐射强度"],
    a: 1,
    fig: ["2010-3.png"],
  },
  { id: "m2010-4", y: 2010, num: 4,
    q: "用单轴晶体做成波片以改变入射光的偏振态，其光轴方向 <span class=\"blank\"></span> 方向。",
    o: ["为快轴", "为快轴或慢轴", "为慢轴", "既不可能为快轴方向，也不可能为慢轴"],
    a: 1,
  },
  { id: "m2010-5", y: 2010, num: 5,
    q: "对左旋圆偏振光，<span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">E</span>、<span class=\"m\">H</span> 都左旋", "<span class=\"m\">E</span> 左旋、<span class=\"m\">H</span> 右旋", "<span class=\"m\">E</span> 右旋、<span class=\"m\">H</span> 左旋", "<span class=\"m\">E</span>、<span class=\"m\">H</span> 都右旋"],
    a: 0,
  },
  { id: "m2010-6", y: 2010, num: 6,
    q: "光在 <span class=\"m\">n</span><sub>1</sub>/<span class=\"m\">n</span><sub>2</sub> 界面发生反射和透射，对入射光、反射光和透射光，不变的物理量是 <span class=\"blank\"></span> 。",
    o: ["波长", "波矢", "强度", "频率"],
    a: 3,
  },
  { id: "m2010-7", y: 2010, num: 7,
    q: "波片的主要功能是改变入射光的 <span class=\"blank\"></span> 。",
    o: ["波长", "频率", "偏振态", "强度"],
    a: 2,
  },
  { id: "m2010-8", y: 2010, num: 8,
    q: "现有对于波长 1.06 μm 入射光的 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span> 光学薄膜，且 <span class=\"m\">n</span><sub>1</sub> > <span class=\"m\">n</span><sub>0</sub>、<span class=\"m\">n</span><sub>2</sub>，该光学薄膜对于波长 0.53 μm 的入射光 <span class=\"blank\"></span> 。",
    o: ["增反", "增透", "产生全反射", "既不增反也不增透"],
    a: 3,
  },
  { id: "m2010-9", y: 2010, num: 9,
    q: "沿 KDP 晶体 Z(光)轴正向分别施加强度为 400 V/mm 和 100 V/mm 的电场，记相应的新的晶体主轴 <span class=\"m\">x</span>′ 相对于零电场时主轴 <span class=\"m\">x</span> 的旋转角分别为 α<sub>1</sub>、α<sub>2</sub>，则 α<sub>2</sub>/α<sub>1</sub> <span class=\"blank\"></span> 。",
    o: ["=1", "=2", "=4", ">2"],
    a: 0,
  },
  { id: "m2010-10", y: 2010, num: 10,
    q: "如果光波的波矢 <span class=\"m\">K</span> 与晶体某一光轴方向平行，则可以断定其场矢量 <span class=\"m\">E</span> 和相应的电位移矢量 <span class=\"m\">D</span> <span class=\"blank\"></span> 。",
    o: ["一定平行", "一定垂直", "可能平行", "可能垂直"],
    a: 0,
  },
  { id: "m2010-11", y: 2010, num: 11,
    q: "两束光发生干涉的必要条件是具有相同的 <span class=\"blank\"></span> 。",
    o: ["强度", "波长", "相位", "偏振态"],
    a: 1,
  },
  { id: "m2010-12", y: 2010, num: 12,
    q: "圆偏振光经 1/4 波片后变成 <span class=\"blank\"></span> 。",
    o: ["线偏振光", "椭圆偏振光", "自然光", "部分偏振光"],
    a: 0,
  },
  { id: "m2010-13", y: 2010, num: 13,
    q: "晶体的介电张量一般有 <span class=\"blank\"></span> 个独立的张量元。",
    o: ["6", "7", "8", "9"],
    a: 0,
  },
  { id: "m2010-14", y: 2010, num: 14,
    q: "由 A、B 两只材料、结构相同的激光器发出的激光具非常相近的强度、波长及偏振方向，这两束激光 <span class=\"blank\"></span> 。",
    o: ["相干", "可能相干", "不相干", "无法确定是否相干"],
    a: 2,
  },
  { id: "m2010-15", y: 2010, num: 15,
    q: "喇曼散射和瑞利散射的根本区别在于散射光和入射光的 <span class=\"blank\"></span> 不同。",
    o: ["强度", "波长", "相位", "偏振度"],
    a: 1,
  },
  { id: "m2010-16", y: 2010, num: 16,
    q: "四个复数 exp[−<span class=\"m\">i</span>(ω<span class=\"m\">t</span> − <span class=\"m\">kz</span>)]、exp[+<span class=\"m\">i</span>(ω<span class=\"m\">t</span> − <span class=\"m\">kz</span>)]、exp[−<span class=\"m\">i</span>(<span class=\"m\">kz</span> − ω<span class=\"m\">t</span>)]和 exp[+<span class=\"m\">i</span>(<span class=\"m\">kz</span> − ω<span class=\"m\">t</span>)] 表示的是 <span class=\"blank\"></span> 列光波。",
    o: ["1", "2", "3", "4"],
    a: 0,
  },
  { id: "m2010-17", y: 2010, num: 17,
    q: "在白光入射 F-P 腔所形成的的干涉图样中，同一级圆环中相应于颜色从兰到红的空间位置是 <span class=\"blank\"></span> 。",
    o: ["由外到里", "由里到外", "不变", "随机变化"],
    a: 0,
  },
  { id: "m2010-18", y: 2010, num: 18,
    q: "F-P 腔两平行腔面间的距离 <span class=\"m\">h</span> 变化时，其干涉图样的中心 <span class=\"blank\"></span> 。",
    o: ["色散率保持最低", "光强度保持最亮", "光强度保持最低", "光强度会发生变化"],
    a: 3,
  },
  { id: "m2010-19", y: 2010, num: 19,
    q: "有右图所示的单缝衍射系统，在单缝右边距离单缝 <span class=\"m\">c</span>、<span class=\"m\">d</span> 处分别观察到图中单缝右边（a）、（b）所示的衍射图样。由（a）、（b）两幅衍射图样可以断定相应于衍射图样的观察距离 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">c</span>=<span class=\"m\">d</span>", "<span class=\"m\">c</span>><span class=\"m\">d</span>", "<span class=\"m\">c</span><<span class=\"m\">d</span>", "<span class=\"m\">c</span>/<span class=\"m\">d</span>=2"],
    a: 1,
    fig: ["2010-19.png"],
  },
  { id: "m2010-20", y: 2010, num: 20,
    q: "自然光分别通过左、右旋晶体后，出射光 <span class=\"blank\"></span> 。",
    o: ["分别为左旋圆偏振光和右旋圆偏振光", "都为完全偏振光", "都为部分偏振光", "都为自然光"],
    a: 3,
  },
  { id: "m2010-21", y: 2010, num: 21,
    q: "圆偏振光通过半波片后，出射光为 <span class=\"blank\"></span> 。",
    o: ["与入射光旋转方向相同的圆偏振光", "线偏振光", "与入射光旋转方向相反的圆偏振光", "部分偏振光"],
    a: 2,
  },
  { id: "m2011-1", y: 2011, num: 1,
    q: "波长为 0.50 μm 的光波正入射到每毫米 600 线的平面光栅，所能观察到的衍射条纹的最高级次为 <span class=\"blank\"></span> 。",
    o: ["2", "3", "4", "5"],
    a: 1,
  },
  { id: "m2011-2", y: 2011, num: 2,
    q: "决定平行平板干涉属双光束干涉还是多光束干涉的关键因素是平板的 <span class=\"blank\"></span> 。",
    o: ["平行度", "厚度", "反射率", "折射率"],
    a: 2,
  },
  { id: "m2011-3", y: 2011, num: 3,
    q: "在对称平板双光束干涉中，无论是等厚干涉还是等倾干涉，也无论是平板介质的折射率较高还是平板两侧介质的折射率较高，对于产生干涉的两束光波，除一束光波在平板介质中往返一趟所产生的相位差之外，由于上、下界面反射所产生的附加相位差总是 <span class=\"blank\"></span> 。",
    o: ["等于 π", "等于 0", "等于 π 或 0", "∈[0, π]"],
    a: 0,
  },
  { id: "m2011-4", y: 2011, num: 4,
    q: "自然光正入射，其反射光必为 <span class=\"blank\"></span> 。",
    o: ["椭圆偏振光", "线偏振光", "部分偏振光", "自然光"],
    a: 3,
  },
  { id: "m2011-5", y: 2011, num: 5,
    q: "如果不考虑吸收、散射等损耗机制，光通过波片之后，强度 <span class=\"blank\"></span> 。",
    o: ["增加", "降低", "不变", "不定"],
    a: 2,
  },
  { id: "m2011-6", y: 2011, num: 6,
    q: "应用波片改变光波的偏振态时，光波传播方向（波矢）一般 <span class=\"blank\"></span> 。",
    o: ["平行于快轴", "平行于慢轴", "平行于快、慢轴", "垂直于快、慢轴"],
    a: 3,
  },
  { id: "m2011-7", y: 2011, num: 7,
    q: "圆偏振光 <span class=\"m\">E</span><sub>x</sub>、<span class=\"m\">E</span><sub>y</sub> 之相位差为 <span class=\"blank\"></span> 。",
    o: ["0", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">2</span></span>", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">4</span></span>", "π"],
    a: 1,
  },
  { id: "m2011-8", y: 2011, num: 8,
    q: "对于单轴晶体中的 <span class=\"m\">O</span> 光，以下说法正确的是 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">E</span> 矢量平行于 <span class=\"m\">D</span> 矢量", "<span class=\"m\">E</span> 矢量和 <span class=\"m\">D</span> 矢量一般有一定夹角", "偏振方向平行于光轴", "<span class=\"m\">K</span> 矢量垂直于 <span class=\"m\">E</span> 矢量"],
    a: null,  note: "答案册给了 A、D 两种说法，本题不计对错。",
  },
  { id: "m2011-9", y: 2011, num: 9,
    q: "沿 <span class=\"m\">Z</span> 轴方向施加电场的 KDP 晶体一般呈 <span class=\"blank\"></span> 。",
    o: ["单轴晶体", "双轴晶体", "各向同性晶体", "均匀媒质"],
    a: 1,
  },
  { id: "m2011-10", y: 2011, num: 10,
    q: "光能可能转变为其它形式能量的物理现象是 <span class=\"blank\"></span> 。",
    o: ["光的吸收", "光的干涉", "光的衍射", "光的散射"],
    a: 0,
  },
  { id: "m2011-11", y: 2011, num: 11,
    q: "沿 <span class=\"m\">Z</span> 方向传播的光波在 <span class=\"m\">X</span>、<span class=\"m\">Y</span> 方向上的空间频率 <span class=\"m\">f</span><sub>x</sub> 、 <span class=\"m\">f</span><sub>y</sub> <span class=\"blank\"></span> 。",
    o: ["不相等", "都等于 0", "都趋于无穷大", "随空间变化"],
    a: 1,
  },
  { id: "m2011-12", y: 2011, num: 12,
    q: "对于单层光学薄膜，增透膜和增反膜的光学厚度 <span class=\"blank\"></span> 。",
    o: ["分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>"],
    a: 2,
  },
  { id: "m2011-13", y: 2011, num: 13,
    q: "钠蒸气对 <span class=\"m\">λ</span> = 588.9 nm 的光呈强烈吸收，由此可以断定钠蒸气对 588.9 nm 附近的光呈现 <span class=\"blank\"></span> 。",
    o: ["正常色散", "反常色散", "零色散", "Mie 散射"],
    a: 1,
  },
  { id: "m2011-14", y: 2011, num: 14,
    q: "在闪耀光栅中，使刻槽面与光栅面成 <span class=\"m\">θ</span> 角，其目的是使 <span class=\"blank\"></span> 。",
    o: ["干涉零级与衍射零级在空间分开", "干涉零级与衍射零级在空间重合", "条纹变宽", "自由光谱范围增大"],
    a: 0,
    fig: ["2011-14.png"],
  },
  { id: "m2011-15", y: 2011, num: 15,
    q: "在均匀平面波垂直入射的芙琅和费多缝衍射中，相邻缝的衍射图样 <span class=\"blank\"></span> 。",
    o: ["相同", "相似， 但空间位置不同", "相似，但空间位置平移缝距 <span class=\"m\">d</span>", "强弱互补"],
    a: 0,
  },
  { id: "m2011-16", y: 2011, num: 16,
    q: "线偏振光通过半波片后，一定是 <span class=\"blank\"></span> 。",
    o: ["圆偏振光", "线偏振光", "椭圆偏振光", "自然光"],
    a: 1,
  },
  { id: "m2011-17", y: 2011, num: 17,
    q: "如果用双轴晶体制制作波片，且希望用较薄的晶片产生尽可能大的光程差，其光轴方向 <span class=\"blank\"></span> 方向。",
    o: ["为快轴", "为快轴或慢轴", "为慢轴", "既不为快轴方向，也不为慢轴"],
    a: 3,
  },
  { id: "m2011-18", y: 2011, num: 18,
    q: "线偏振光偏振面与半波片的快轴（ <span class=\"m\">Z</span> 轴正向）夹角为+30°，经半波片后，出射光偏振面与 <span class=\"m\">Z</span> 轴正向夹角为 <span class=\"blank\"></span> 度。",
    o: ["+ 60", "+ 90", "- 30", "- 60"],
    a: 2,
    fig: ["2011-18.png"],
  },
  { id: "m2011-19", y: 2011, num: 19,
    q: "光栅刻痕密度不变，入射光波长不变，入射光束与光栅的相对方向不变，且全投射在光栅面内，如果光束横截面面积减小，光栅的分辨能力会 <span class=\"blank\"></span> 。",
    o: ["降低", "升高", "= 0", "不变"],
    a: 0,
  },
  { id: "m2011-20", y: 2011, num: 20,
    q: "四个复数 <span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">r</span></span>exp[−<span class=\"m\">i</span>(<span class=\"m\">ωt</span>−<span class=\"m\">kr</span>)]、<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">r</span></span>exp[+<span class=\"m\">i</span>(<span class=\"m\">ωt</span>−<span class=\"m\">kr</span>)]、<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">r</span></span>exp[−<span class=\"m\">i</span>(<span class=\"m\">kr</span>−<span class=\"m\">ωt</span>)] 和 <span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">r</span></span>exp[+<span class=\"m\">i</span>(<span class=\"m\">kr</span>−<span class=\"m\">ωt</span>)] 表示的是 <span class=\"blank\"></span> 列光波。",
    o: ["1 列发散球面波", "2 列发散球面波和 2 列会聚球面波", "1 列会聚球面波", "3 列发散球面波和 1 列会聚球面波"],
    a: 0,
  },
  { id: "m2012-1", y: 2012, num: 1,
    q: "当光波在两种不同介质中的振幅相等时， <span class=\"blank\"></span> 。",
    o: ["其强度相等。", "其强度不相等。", "其强度比不确定。", "其强度比等于两种介质的折射率之比。"],
    a: 3,
  },
  { id: "m2012-2", y: 2012, num: 2,
    q: "在同一介质中，圆偏振光的电场为 <span class=\"m\">E</span>，线偏振光的电场振幅为 <span class=\"m\">E</span>，两光的光强之间的关系为 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">I</span><sub>圆</sub>=<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub>=2<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub><<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub>=√<span class=\"rad\">2</span><span class=\"m\">I</span><sub>线</sub>"],
    a: 1,
  },
  { id: "m2012-3", y: 2012, num: 3,
    q: "在相同时间内，同一单色光在空气和在玻璃中 <span class=\"blank\"></span> 。",
    o: ["传播的路程相等、光程相等。", "传播的路程相等、光程不相等。", "传播的路程不相等、光程相等。", "传播的路程不相等、光程不相等。"],
    a: 2,
  },
  { id: "m2012-4", y: 2012, num: 4,
    q: "光从折射率小的介质中正入射到折射率大的介质表面时，相对于入射光的电场和磁场，反射光的 <span class=\"blank\"></span> 。",
    o: ["电场和磁场都无相位变化。", "电场和磁场都有 π 相位突变。", "电场有 π 相位突变，磁场无相位变化。", "电场无相位变化，磁场有 π 相位突变。"],
    a: 2,
  },
  { id: "m2012-5", y: 2012, num: 5,
    q: "自然光正入射，其折射光为 <span class=\"blank\"></span> 。",
    o: ["椭圆偏振光", "线偏振光", "部分偏振光", "自然光"],
    a: 3,
  },
  { id: "m2012-6", y: 2012, num: 6,
    q: "光在界面发生全反射时，在折射率小的介质中的电场 <span class=\"blank\"></span> 。",
    o: ["等于零。", "随离界面距离增加按指数规律衰减。", "等于常数。", "随离界面距离增加按指数规律增加。"],
    a: 1,
  },
  { id: "m2012-7", y: 2012, num: 7,
    q: "单色平行光垂直照射在薄膜上，经上下两表面反射的两束光发生干涉，若薄膜的厚度为 <span class=\"m\">h</span>，且 <span class=\"m\">n</span><sub>1</sub><<span class=\"m\">n</span><sub>2</sub>><span class=\"m\">n</span><sub>3</sub>， <span class=\"m\">λ</span><sub>1</sub> 为入射光在 <span class=\"m\">n</span><sub>1</sub> 中的波长，则两束反射光的光程差为 <span class=\"blank\"></span> 。",
    o: ["2<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span>", "2<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span>+<span class=\"m\">λ</span><sub>1</sub>/(2<span class=\"m\">n</span><sub>1</sub>)", "2 <span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span>+<span class=\"m\">n</span><sub>1</sub><span class=\"m\">λ</span><sub>1</sub>/2", "2 <span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span>+<span class=\"m\">n</span><sub>2</sub><span class=\"m\">λ</span><sub>1</sub>/2"],
    a: 2,
  },
  { id: "m2012-8", y: 2012, num: 8,
    q: "在白光入射的等倾干涉中，同级圆环中相应于颜色紫到红各色光的空间位置是 <span class=\"blank\"></span> 。",
    o: ["由外到里。", "由里到外。", "不变。", "随机变化。"],
    a: 0,
  },
  { id: "m2012-9", y: 2012, num: 9,
    q: "把一平凸透镜放在平板玻璃上构成牛顿环装置，当平凸透镜慢慢地向上平移时，由反射光形成的牛顿环 <span class=\"blank\"></span> 。",
    o: ["向中心收缩， 条纹间隔不变。", "向中心收缩，中心呈明暗交替变化。", "向外扩张，中心呈明暗交替变化。", "向外扩张，条纹间隔变大。"],
    a: 1,
  },
  { id: "m2012-10", y: 2012, num: 10,
    q: "当 F-P 腔两相对平行腔面间的距离增加时，其 <span class=\"blank\"></span> 。",
    o: ["分辨能力增强。", "分辨能力降低。", "自由光谱范围增大。", "最小可分辨波长差增大。"],
    a: 0,
  },
  { id: "m2012-11", y: 2012, num: 11,
    q: "关于光的空间相干性，下列说法不正确的是 <span class=\"blank\"></span> 。",
    o: ["光场的空间相干性来源于普通扩展光源不同部分发出的光的不相干性。", "普通光源的空间扩展越大，其光场的空间相干范围越小。", "光的空间相干性反映了光波场的横向相干性。", "空间相干性与光波的波列长度有关。"],
    a: 3,
  },
  { id: "m2012-12", y: 2012, num: 12,
    q: "在如图所示的单缝夫琅禾费衍射装置中，将单缝宽度 <span class=\"m\">a</span> 稍稍变宽，同时使单缝沿 <span class=\"m\">y</span> 轴正方向作微小位移，则屏幕 <span class=\"m\">C</span> 上的中央衍射条纹将 <span class=\"blank\"></span> 。",
    o: ["变窄，同时向上移。", "变窄，同时向下移。", "变窄，不移动。", "变宽，同时向上移。"],
    a: 2,
    fig: ["2012-12.png"],
  },
  { id: "m2012-13", y: 2012, num: 13,
    q: "光栅常数 <span class=\"m\">d</span> 增加（其它条件不变）时，则 <span class=\"blank\"></span> 。",
    o: ["自由光谱范围增大", "色散能力增大", "分辨能力增强", "分辨能力不变"],
    a: 3,
  },
  { id: "m2012-14", y: 2012, num: 14,
    q: "地球与月球相距 3.8×10<sup>5</sup> km，用口径为 1m 的天文望远镜（取光波长 <span class=\"m\">λ</span> = 550 nm）能分辨月球表面两点的最小距离约为 <span class=\"blank\"></span> 。",
    o: ["96 m", "128 m", "255 m", "510 m"],
    a: 2,
  },
  { id: "m2012-15", y: 2012, num: 15,
    q: "如图所示，由入缝 A 进入的白光经反射光栅衍射分光后由出缝 B 射出。现保持入缝、出缝的位置不变，使光栅绕 C 轴按顺时针方向旋转时，同级衍射光由出缝 B 射出的光 <span class=\"blank\"></span> 。",
    o: ["呈紫色", "呈红色", "由紫转红", "由红转紫"],
    a: 2,
    fig: ["2012-15.png"],
  },
  { id: "m2012-16", y: 2012, num: 16,
    q: "若一个菲涅耳波带片只将前 5 个偶数半波带挡住，其余部分都通光，则中心轴上相应衍射场点的光强与自由传播时此处光强之比为 <span class=\"blank\"></span> 。",
    o: ["10", "11", "100", "121"],
    a: 3,
  },
  { id: "m2012-17", y: 2012, num: 17,
    q: "光波沿晶体光轴方向传播时，其电场强度矢量 <span class=\"m\">E</span> 和相应的电位移矢量 <span class=\"m\">D</span> <span class=\"blank\"></span> 。",
    o: ["一定平行", "一定垂直", "可能平行", "可能垂直."],
    a: 0,
  },
  { id: "m2012-18", y: 2012, num: 18,
    q: "折射率椭球中的矢径方向代表 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">E</span> 矢量的方向", "<span class=\"m\">D</span> 矢量的方向", "<span class=\"m\">k</span> 矢量的方向", "<span class=\"m\">s</span> 矢量的方向"],
    a: 1,
  },
  { id: "m2012-19", y: 2012, num: 19,
    q: "波片“快轴”的物理意义是 <span class=\"blank\"></span> 。",
    o: ["电场振动方向沿快轴方向的光波具较快的传播速度、较小折射率。", "磁场振动方向沿快轴方向的光波具较快的传播速度、较大折射率。", "<span class=\"m\">k</span> 方向沿快轴方向的光波具较快的传播速度、较小折射率。", "<span class=\"m\">s</span> 方向沿快轴方向的光波具较快的传播速度、较大折射率。"],
    a: 0,  note: "原卷本题四个选项没有印 A/B/C/D 标号，此处按卷面顺序编号。",
  },
  { id: "m2012-20", y: 2012, num: 20,
    q: "自然光通过半波片后，一定是 <span class=\"blank\"></span> 。",
    o: ["线偏振光", "圆偏振光", "椭圆偏振光", "自然光"],
    a: 3,
  },
  { id: "m2012-21", y: 2012, num: 21,
    q: "如图所示，当偏振片 <span class=\"m\">P</span> 旋转一周时，若 <span class=\"m\">I</span> 变，但是无消光现象，则入射光是 <span class=\"blank\"></span> 。",
    o: ["部分偏振光", "椭圆偏振光", "圆偏振光", "部分偏振光或椭圆偏振光"],
    a: 3,
    fig: ["2012-21.png"],
  },
  { id: "m2012-22", y: 2012, num: 22,
    q: "强度为 <span class=\"m\">I</span><sub>i</sub> 的部分偏振光由一束自然光和一束圆偏振光组成，其强度分别为 <span class=\"m\">I</span><sub>N</sub> 和 <span class=\"m\">I</span><sub>C</sub>。让该光束依次通过 1/4 波片和检偏器，旋转检偏器，发现出射的最小光强为 <span class=\"m\">I</span><sub>i</sub>/4，可以断定 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">I</span><sub>N</sub>=<span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub>><span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub><<span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub>=2<span class=\"m\">I</span><sub>C</sub>"],
    a: 0,
  },
  { id: "m2012-23", y: 2012, num: 23,
    q: "光强为 <span class=\"m\">I</span><sub>0</sub> 的光束经过厚度为 <span class=\"m\">d</span> 的吸收介质后，强度减为 <span class=\"m\">I</span><sub>0</sub>/2，若将此吸收介质的厚度增加到 3<span class=\"m\">d</span>， 光强将减少为 <span class=\"blank\"></span> 。",
    o: ["<span class=\"m\">I</span><sub>0</sub>/3", "<span class=\"m\">I</span><sub>0</sub>/6", "<span class=\"m\">I</span><sub>0</sub>/8", "<span class=\"m\">I</span><sub>0</sub>/9"],
    a: 2,
  },
  { id: "m2012-24", y: 2012, num: 24,
    q: "相对于入射光波， 散射光波频率发生变化的散射是 <span class=\"blank\"></span> 。",
    o: ["瑞利散射", "米氏散射", "线性散射", "拉曼散射"],
    a: 3,
  },
  { id: "m2013-1", y: 2013, num: 1,
    q: "单色的自然光和圆偏振光都可以视为振幅相等且振动方向垂直的两线偏振光的合成，它们之间的主要区别是 <span class=\"blank\"></span> 。",
    o: ["两线偏振光的振动方向是否一定", "两线偏振光的相位差是否一定", "两线偏振光的传播方向是否相同", "两线偏振光的频率是否相同"],
    a: 1,
  },
  { id: "m2013-2", y: 2013, num: 2,
    q: "右旋圆偏振光从空气中垂直入射到玻璃表面，其反射光是 <span class=\"blank\"></span> 。",
    o: ["右旋圆偏振光", "左旋圆偏振光", "右旋椭圆偏振光", "左旋椭圆偏振光"],
    a: 1,
  },
  { id: "m2013-3", y: 2013, num: 3,
    q: "光波在界面发生反射和折射时，对于入射光、反射光和折射光，不变的量是 <span class=\"blank\"></span> 。",
    o: ["波长", "波矢", "光强", "频率"],
    a: 3,
  },
  { id: "m2013-4", y: 2013, num: 4,
    q: "光波在界面发生折射时，不影响折射光传播方向的因素是 <span class=\"blank\"></span> 。",
    o: ["入射角", "界面两侧介质的折射率比值", "入射光的偏振态", "界面两侧介质的电磁特性参数"],
    a: 2,
  },
  { id: "m2013-5", y: 2013, num: 5,
    q: "振动面平行于入射面的线偏振光以布儒斯特角从光密介质投射到与光疏介质的分界面，透射光与入射光的光强之比为 <span class=\"blank\"></span> 。",
    o: ["大于 1", "小于 1", "等于 1", "不确定"],
    a: 0,
  },
  { id: "m2013-6", y: 2013, num: 6,
    q: "光波在界面发生全反射的条件不包括 <span class=\"blank\"></span> 。",
    o: ["从光密介质到光疏介质", "光波为线偏振光", "入射角为全反射临界角", "入射角大于全反射临界角"],
    a: 1,
  },
  { id: "m2013-7", y: 2013, num: 7,
    q: "薄平板置于同一均匀介质中的分振幅双光束干涉中，两透射光束间的附加相位差是 <span class=\"blank\"></span> 。",
    o: ["等于 π", "等于 0", "不确定", "在 0 和 π 之间"],
    a: 1,
  },
  { id: "m2013-8", y: 2013, num: 8,
    q: "牛顿环条纹中，最接近中心环的色散 <span class=\"blank\"></span> 。",
    o: ["最强", "最弱", "等于常数", "等于零"],
    a: 1,
  },
  { id: "m2013-9", y: 2013, num: 9,
    q: "在迈克耳孙干涉仪的一支光路中，放入一片折射率为 <span class=\"m\">n</span> 的透明介质薄膜后，测出两束光的光程差的改变量为一个波长 <span class=\"m\">λ</span>，则薄膜的厚度是 <span class=\"blank\"></span> 。",
    o: ["<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>", "<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2n</span></span>", "<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">n</span></span>", "<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2(n−1)</span></span>"],
    a: 1,
  },
  { id: "m2013-10", y: 2013, num: 10,
    q: "当 F-P 腔的反射率 <span class=\"m\">R</span> 增加时，其色分辨能力 <span class=\"blank\"></span> 。",
    o: ["下降", "恒定不变", "趋于零", "增加"],
    a: 3,
  },
  { id: "m2013-11", y: 2013, num: 11,
    q: "关于光的时间相干性，下列说法不正确的是 <span class=\"blank\"></span> 。",
    o: ["光场的时间相干性来源于普通光源的原子发光持续时间有限。", "光场的时间相干性与光源的光谱展宽无关。", "光场的时间相干性反映了光场的纵向相干性。", "光波的波列越长，其光场的时间相干性越好。"],
    a: 1,
  },
  { id: "m2013-12", y: 2013, num: 12,
    q: "在如图所示的单缝夫琅禾费衍射实验中，若将单缝沿透镜光轴方向向透镜平移，则屏幕上的衍射条纹 <span class=\"blank\"></span> 。",
    o: ["间距变大", "间距变小", "衍射级次增多", "间距不变，但明暗条纹的位置互换"],
    a: 2,
    fig: ["2013-12.png"],
  },
  { id: "m2013-13", y: 2013, num: 13,
    q: "孔径相同的微波望远镜和光学望远镜比较，前者的分辨本领小的原因是 <span class=\"blank\"></span> 。",
    o: ["星体发身射的微波能量比可见光能量弱。", "微波更易被大气的尘埃散射。", "微波更易被大气所吸收。", "微波波长比光波波长更长。"],
    a: 3,  note: "选项 A 原卷印作「星体发身射的微波能量…」，「发身射」应为「发射」，此处照原卷。",
  },
  { id: "m2013-14", y: 2013, num: 14,
    q: "人眼观察远处物体时，刚好能被眼睛分辨的两物点对瞳孔中心的张角称为人眼的最小分辨角。若瞳孔直径为 <span class=\"m\">D</span>，光在空气中的波长为 <span class=\"m\">λ</span>，人眼玻璃状液的折射率为 <span class=\"m\">n</span>， 则人眼的最小分辨角为 <span class=\"blank\"></span> 。",
    o: ["1.22<span class=\"m\">λ</span>/<span class=\"m\">D</span>", "1.22<span class=\"m\">λ</span>/<span class=\"m\">nD</span>", "0.61<span class=\"m\">λ</span>/<span class=\"m\">nD</span>", "1.22<span class=\"m\">λn</span>/<span class=\"m\">D</span>"],
    a: 0,
  },
  { id: "m2013-15", y: 2013, num: 15,
    q: "一闪耀光栅的主闪耀波长为 12 μm，对它不呈现闪耀的波长是 <span class=\"blank\"></span> 。",
    o: ["2 μm", "3 μm", "5 μm", "6 μm"],
    a: 2,
  },
  { id: "m2013-16", y: 2013, num: 16,
    q: "一个波带片的孔径内有 10 个半波带，让其中的 5 个奇数带通光， 5 个偶数带被挡住，则中心轴上相应衍射场点的光强为此处自由传播时光强的 <span class=\"blank\"></span> 倍。",
    o: ["5", "10", "20", "100"],
    a: 3,
  },
  { id: "m2013-17", y: 2013, num: 17,
    q: "在单轴晶体中 e 光的波矢 <span class=\"m\">k</span> 与其坡印廷矢量 <span class=\"m\">S</span> 的方向不一致，是由于 <span class=\"blank\"></span> 。",
    o: ["能流速度与波面速度不相同", "电场强度矢量 <span class=\"m\">E</span> 与电位移矢量 <span class=\"m\">D</span> 的方向不一致", "折射率不同于光线折射率", "主折射率不相等"],
    a: 3,
  },
  { id: "m2013-18", y: 2013, num: 18,
    q: "光束经渥拉斯顿棱镜后，出射光只有一束，入射光应为 <span class=\"blank\"></span> 。",
    o: ["自然光", "部分偏振光", "圆偏振光", "线偏振光"],
    a: 3,
  },
  { id: "m2013-19", y: 2013, num: 19,
    q: "应用波片时，波矢方向一般 <span class=\"blank\"></span> 。",
    o: ["平行于快轴", "平行于慢轴", "平行于快轴和慢轴", "垂直于快轴和慢轴"],
    a: 3,
  },
  { id: "m2013-20", y: 2013, num: 20,
    q: "如图所示，当偏振片 <span class=\"m\">P</span> 旋转一周时，若 <span class=\"m\">I</span> 无变化，则入射光不可能是 <span class=\"blank\"></span> 。",
    o: ["自然光", "圆偏振光", "椭圆偏振光", "自然光与圆偏振光的组合"],
    a: 2,
    fig: ["2013-20.png"],
  },
  { id: "m2013-21", y: 2013, num: 21,
    q: "线偏振光通过四分之一波片后， <span class=\"blank\"></span> 。",
    o: ["一定是圆偏振光", "不一定是圆偏振光", "是线偏振光", "是振动面有旋转的线偏振光"],
    a: 1,
  },
  { id: "m2013-22", y: 2013, num: 22,
    q: "沿 KDP 晶体的光轴方向施加电场后，KDP 晶体成为 <span class=\"blank\"></span> 。",
    o: ["单轴晶体", "双轴晶体", "各向同性晶体", "光性学质不确定"],
    a: 1,
  },
  { id: "m2013-23", y: 2013, num: 23,
    q: "介质复折射率的虚部描述了光的 <span class=\"blank\"></span> 特性。",
    o: ["吸收", "色散", "散射", "衍射"],
    a: 0,
  },
  { id: "m2013-24", y: 2013, num: 24,
    q: "晴朗的天空呈现蓝色，是由于大气对日光的 <span class=\"blank\"></span> 。",
    o: ["反射", "衍射", "色散", "散射"],
    a: 3,
  },
  { id: "m2013-25", y: 2013, num: 25,
    q: "下列有关光色散的描述中，不正确的描述是 <span class=\"blank\"></span> 。",
    o: ["光波的相速与群速的区别来源于介质的色散。", "玻璃三棱镜对日光形成的彩色光带光谱中，红光比蓝光偏折更大。", "一种介质发生反常色散的波长区，也是该介质反生强烈吸收的波长区。", "介质的折射率随光波频率增大而减小的现象就是反常色散。"],
    a: 1,  note: "选项 C 原卷印作「…反生强烈吸收的波长区。」，「反生」应为「发生」，此处照原卷。",
  },
  { id: "m2014-1", y: 2014, num: 1,
    q: "由电磁场的边界条件不能确定透射波的<span class=\"blank\"></span>。",
    o: ["传播方向", "电矢量振幅", "偏振状态", "色散"],
    a: 3,
  },
  { id: "m2014-2", y: 2014, num: 2,
    q: "光波正入射时，界面上的反射特性和透射特性与下列因素无关的是<span class=\"blank\"></span>。",
    o: ["界面两侧介质的折射率", "入射光的偏振状态", "界面两侧介质的电磁特性", "界面两侧介质中的光速"],
    a: 1,
  },
  { id: "m2014-3", y: 2014, num: 3,
    q: "振动面不平行也不垂直于入射面的线偏振光经界面全反射后，反射光通常为<span class=\"blank\"></span>。",
    o: ["线偏振光", "圆偏振光", "椭圆偏振光", "部分偏振光"],
    a: 2,
  },
  { id: "m2014-4", y: 2014, num: 4,
    q: "光波在界面发生全反射时，关于第二介质中存的透射波，下列说法不正确的是<span class=\"blank\"></span>。",
    o: ["存在透射波是电磁场边界条件所要求的", "透射波是非均匀平面波", "透射波沿界面法向急剧衰减", "透射波向第二个质内部传输能量"],
    a: 3,
  },
  { id: "m2014-5", y: 2014, num: 5,
    q: "关于光功率透射率和光强透射率的关系，正确的是<span class=\"blank\"></span>。",
    o: ["两透射率相等", "两透射率总是不相等", "正入射时两透射率相等", "对应分量的两透射率相等"],
    a: 2,
  },
  { id: "m2014-6", y: 2014, num: 6,
    q: "一时谐平面波振幅为 <span class=\"m\">E</span><sub>0</sub>、在坐标原点的初相位为φ<sub>0</sub>、波矢 <span class=\"m\">k</span> 在 <span class=\"m\">x</span><span class=\"m\">o</span><span class=\"m\">y</span> 平面内与 <span class=\"m\">y</span> 轴夹角成θ，此平面波的复振幅是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">Ẽ</span>(<span class=\"m\">r</span>) = <span class=\"m\">E</span><sub>0</sub><span class=\"m\">e</span><sup>i[<span class=\"m\">k</span>(<span class=\"m\">x</span>sinθ+<span class=\"m\">y</span>cosθ)−φ<sub>0</sub>]</sup>", "<span class=\"m\">Ẽ</span>(<span class=\"m\">r</span>) = <span class=\"m\">E</span><sub>0</sub><span class=\"m\">e</span><sup>i[<span class=\"m\">k</span>(<span class=\"m\">x</span>sinθ+<span class=\"m\">y</span>cosθ)+φ<sub>0</sub>]</sup>", "<span class=\"m\">Ẽ</span>(<span class=\"m\">r</span>) = <span class=\"m\">E</span><sub>0</sub><span class=\"m\">e</span><sup>i[−<span class=\"m\">k</span>(<span class=\"m\">x</span>sinθ+<span class=\"m\">y</span>cosθ)−φ<sub>0</sub>]</sup>", "<span class=\"m\">Ẽ</span>(<span class=\"m\">r</span>) = <span class=\"m\">E</span><sub>0</sub><span class=\"m\">e</span><sup>i[<span class=\"m\">k</span>(<span class=\"m\">x</span>cosθ+<span class=\"m\">y</span>sinθ)−φ<sub>0</sub>]</sup>"],
    a: 0,
  },
  { id: "m2014-7", y: 2014, num: 7,
    q: "偏振度的计算式 <span class=\"m\">P</span> = <span class=\"frac\"><span class=\"n\"><span class=\"m\">I</span><sub>M</sub> − <span class=\"m\">I</span><sub>m</sub></span><span class=\"d\"><span class=\"m\">I</span><sub>M</sub> + <span class=\"m\">I</span><sub>m</sub></span></span> 可适用于<span class=\"blank\"></span>。",
    o: ["椭圆偏振光", "所有的部分偏振光", "线偏振光与自然光组合的部分偏振光", "圆偏振光与自然光组合的部分偏振光"],
    a: 2,
  },
  { id: "m2014-8", y: 2014, num: 8,
    q: "群速度的概念适用于<span class=\"blank\"></span>。",
    o: ["复色光，无色散介质。", "单色光、色散介质。", "准单色光、弱色散介质。", "准单色光、强色散介质。"],
    a: 2,
  },
  { id: "m2014-9", y: 2014, num: 9,
    q: "反射光相对于入射光无“半波损失”的情形是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">n</span><sub>1</sub> < <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">θ</span><sub>1</sub> = 0", "<span class=\"m\">n</span><sub>1</sub> > <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">θ</span><sub>1</sub> = 0", "<span class=\"m\">n</span><sub>1</sub> > <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">θ</span><sub>1</sub> ≈ 90<sup>0</sup>", "<span class=\"m\">n</span><sub>1</sub> < <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">θ</span><sub>1</sub> ≈ 90<sup>0</sup>"],
    a: 1,
  },
  { id: "m2014-10", y: 2014, num: 10,
    q: "如图所示，两反射光之间无“附加光程差”情形是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">n</span><sub>1</sub> = <span class=\"m\">n</span><sub>3</sub> < <span class=\"m\">n</span><sub>2</sub>", "<span class=\"m\">n</span><sub>2</sub> < <span class=\"m\">n</span><sub>1</sub>，<span class=\"m\">n</span><sub>2</sub> < <span class=\"m\">n</span><sub>3</sub>", "<span class=\"m\">n</span><sub>2</sub> > <span class=\"m\">n</span><sub>1</sub>，<span class=\"m\">n</span><sub>2</sub> > <span class=\"m\">n</span><sub>3</sub>", "<span class=\"m\">n</span><sub>1</sub> < <span class=\"m\">n</span><sub>2</sub> < <span class=\"m\">n</span><sub>3</sub>"],
    a: 3,
    fig: ["2014-10.png"],
  },
  { id: "m2014-11", y: 2014, num: 11,
    q: "平板的等倾干涉中，当表面的反射率较低时，通常<span class=\"blank\"></span>。",
    o: ["应用透射光干涉", "应用反射光干涉", "反射光干涉和透射光干涉都可使用", "反射光干涉和透射光干涉都不使用"],
    a: 1,
  },
  { id: "m2014-12", y: 2014, num: 12,
    q: "关于杨氏双缝干涉，下列说法不正确的是<span class=\"blank\"></span>。",
    o: ["光源的横向宽度限制双缝的最大距离。", "光源的谱宽限制观察屏上干涉条纹的横向范围。", "条纹可见度整体随光源谱宽增大而降低。", "在光源临界宽度范围内，条纹可见度整体随光源宽度增大而降低。"],
    a: 1,
  },
  { id: "m2014-13", y: 2014, num: 13,
    q: "迈克尔逊干涉仪中补偿板的作用是<span class=\"blank\"></span>。",
    o: ["消除两光路的不对称性", "补偿两光路的光程差", "在使用白色光源时补偿分光板的色散", "补偿两光路的光强差"],
    a: 2,
  },
  { id: "m2014-14", y: 2014, num: 14,
    q: "如图所示，波长为λ的光正入射时，单层膜能完全消除反射光的条纹是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">n</span><sub>2</sub> < <span class=\"m\">n</span><sub>3</sub>，<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span> = λ/4", "<span class=\"m\">n</span><sub>2</sub> < <span class=\"m\">n</span><sub>3</sub>，<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span> = λ/2", "<span class=\"m\">n</span><sub>2</sub> > <span class=\"m\">n</span><sub>3</sub>，<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span> = λ/2", "<span class=\"m\">n</span><sub>2</sub> = √<span class=\"rad\"><span class=\"m\">n</span><sub>1</sub><span class=\"m\">n</span><sub>3</sub></span>，<span class=\"m\">n</span><sub>2</sub><span class=\"m\">h</span> = λ/4"],
    a: 3,
    fig: ["2014-14.png"],
  },
  { id: "m2014-15", y: 2014, num: 15,
    q: "对于单层光学薄膜，增透膜和增反膜的光学厚度<span class=\"blank\"></span>。",
    o: ["分别为 λ/2 和 λ/4", "分别为 λ/4 和 λ/2", "都等于 λ/4", "都等于 λ/2"],
    a: 2,
  },
  { id: "m2014-16", y: 2014, num: 16,
    q: "双光束等倾干涉图样与多光束等倾干涉图样的主要区别在于<span class=\"blank\"></span>。",
    o: ["光强的极值条件不同", "条纹的细锐度不同", "条纹的形状不同", "条纹的干涉级次分布规律不同"],
    a: 1,
  },
  { id: "m2014-17", y: 2014, num: 17,
    q: "不表征空间相干性的物理量是<span class=\"blank\"></span>。",
    o: ["相干孔径角", "相干面积", "横向相干长度", "纵向相干长度"],
    a: 3,
  },
  { id: "m2014-18", y: 2014, num: 18,
    q: "确定光衍射现象是否明显的要素是<span class=\"blank\"></span>。",
    o: ["光波的波长", "障碍物的尺度", "光波长与障碍物尺度的相对值", "光波的强度"],
    a: 2,
  },
  { id: "m2014-19", y: 2014, num: 19,
    q: "成像光学仪器在像平面的图样是<span class=\"blank\"></span>。",
    o: ["菲涅耳衍射", "夫琅和费衍射", "既不是菲涅耳衍射，也不是夫琅和费衍射。", "菲涅耳衍射和夫琅和费衍射的组合"],
    a: 1,
  },
  { id: "m2014-20", y: 2014, num: 20,
    q: "关于单轴晶体，不正确说法是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">o</span>光的折射率是 <span class=\"m\">n</span><sub>o</sub>，<span class=\"m\">e</span>光的折射率是 <span class=\"m\">n</span><sub>e</sub>。", "离散角是针对 <span class=\"m\">e</span> 光而言的。", "当 <span class=\"m\">k</span> 沿光轴时，<span class=\"m\">D</span> 的方向无限制。", "当 <span class=\"m\">k</span> 垂直于光轴时，<span class=\"m\">S</span> 与 <span class=\"m\">k</span> 的方向一致。"],
    a: 0,
  },
  { id: "m2014-21", y: 2014, num: 21,
    q: "关于双轴晶体，不正确的说法是<span class=\"blank\"></span>。",
    o: ["不存在寻常光。", "当 <span class=\"m\">k</span> 沿光轴时，<span class=\"m\">S</span> 与 <span class=\"m\">k</span> 的方向一致。", "当 <span class=\"m\">k</span> 沿光轴时，<span class=\"m\">D</span> 的方向无限制。", "当 <span class=\"m\">k</span> 沿主轴时，<span class=\"m\">S</span> 与 <span class=\"m\">k</span> 的方向一致。"],
    a: 3,
  },
  { id: "m2014-22", y: 2014, num: 22,
    q: "为使光正入射到单轴晶体内能获得最大的离散角，光轴与通光面的夹角β应满足<span class=\"blank\"></span>。",
    o: ["tgβ = <span class=\"m\">n</span><sub>e</sub>/<span class=\"m\">n</span><sub>o</sub>", "tgβ = <span class=\"m\">n</span><sub>o</sub>/<span class=\"m\">n</span><sub>e</sub>", "tgβ = (<span class=\"m\">n</span><sub>e</sub><sup>2</sup> − <span class=\"m\">n</span><sub>o</sub><sup>2</sup>)/2<span class=\"m\">n</span><sub>e</sub><span class=\"m\">n</span><sub>o</sub>", "tgβ = 2<span class=\"m\">n</span><sub>e</sub><span class=\"m\">n</span><sub>o</sub>/(<span class=\"m\">n</span><sub>e</sub><sup>2</sup> − <span class=\"m\">n</span><sub>o</sub><sup>2</sup>)"],
    a: 1,
  },
  { id: "m2014-23", y: 2014, num: 23,
    q: "光的吸收与散射的主要区别是<span class=\"blank\"></span>。",
    o: ["透射光强是否随传播距离减少", "光能量是否转化为其它形式的能量", "是否是光与物质的相互作用", "吸收系数和散射系数是否与光波波长有关"],
    a: 1,
  },
  { id: "m2014-24", y: 2014, num: 24,
    q: "旭日和夕阳呈红色，是由于大气对日光的<span class=\"blank\"></span>。",
    o: ["反射", "衍射", "色散", "散射"],
    a: 3,
  },
  { id: "m2014-25", y: 2014, num: 25,
    q: "关于色散，下列说法中不正确的是<span class=\"blank\"></span>。",
    o: ["正常色散发生在介质的透明区。", "反常色散发生在介质固有频率附近。", "正常色散是折射率随波长增加而减小的色散。", "反常色散是色散率为负的色散。"],
    a: 3,
  },
  { id: "m2015-1", y: 2015, num: 1,
    q: "可以用复振幅表示光波的条件是<span class=\"blank\"></span>。",
    o: ["线性运算", "非线性运算", "单色光", "复色光"],
    a: 2,
  },
  { id: "m2015-2", y: 2015, num: 2,
    q: "部分偏振光可以表示为<span class=\"blank\"></span>。",
    o: ["两正交线偏振光的叠加", "线偏振光和圆偏振光的叠加", "线偏振光和自然光的叠加", "线偏振光和椭圆偏振光的叠加"],
    a: 2,
  },
  { id: "m2015-3", y: 2015, num: 3,
    q: "自然光正入射到界面，其反射光为<span class=\"blank\"></span>。",
    o: ["椭圆偏振光", "线偏振光", "部分偏振光", "自然光"],
    a: 3,
  },
  { id: "m2015-4", y: 2015, num: 4,
    q: "两振动方向正交、频率相同、振幅相等、相位差为π/2线偏振光叠加成电矢量为 <span class=\"m\">E</span> 的圆偏振光，则此线偏振光的振幅 <span class=\"m\">E</span><sub>0</sub> 为<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">E</span>", "<span class=\"m\">E</span>/2", "<span class=\"m\">E</span>/√<span class=\"rad\">2</span>", "√<span class=\"rad\">2</span><span class=\"m\">E</span>"],
    a: 0,
  },
  { id: "m2015-5", y: 2015, num: 5,
    q: "采用分波面法和分振幅法获得相干光是为了保证<span class=\"blank\"></span>。",
    o: ["叠加光的相位固定", "叠加光的初相位固定", "叠加光的相位差固定", "叠加光的初相位差固定"],
    a: 3,
  },
  { id: "m2015-6", y: 2015, num: 6,
    q: "双光束干涉条纹的可见度与下列因素有关的是<span class=\"blank\"></span>。",
    o: ["叠加光的光强", "叠加光的光强之和", "叠加光的光强之比", "叠加光的光强之差"],
    a: 2,
  },
  { id: "m2015-7", y: 2015, num: 7,
    q: "如图所示，波长为λ的单色光正入射，若要完全消反射，此单层膜要满足的条件是<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">n</span><sub>1</sub> < <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">n</span><sub>1</sub><span class=\"m\">h</span> = (2<span class=\"m\">k</span>+1)<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>，<span class=\"m\">k</span> = 0,1,2,3,…", "<span class=\"m\">n</span><sub>1</sub> = √<span class=\"rad\"><span class=\"m\">n</span><sub>0</sub><span class=\"m\">n</span><sub>2</sub></span>，<span class=\"m\">n</span><sub>1</sub><span class=\"m\">h</span> = (2<span class=\"m\">k</span>+1)<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>，<span class=\"m\">k</span> = 0,1,2,3,…", "<span class=\"m\">n</span><sub>1</sub> = √<span class=\"rad\"><span class=\"m\">n</span><sub>0</sub><span class=\"m\">n</span><sub>2</sub></span>，<span class=\"m\">n</span><sub>1</sub><span class=\"m\">h</span> = (2<span class=\"m\">k</span>+1)<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>，<span class=\"m\">k</span> = 0,1,2,3,…", "<span class=\"m\">n</span><sub>1</sub> > <span class=\"m\">n</span><sub>2</sub>，<span class=\"m\">n</span><sub>1</sub><span class=\"m\">h</span> = (2<span class=\"m\">k</span>+1)<span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>，<span class=\"m\">k</span> = 0,1,2,3,…"],
    a: 1,
    fig: ["2015-7.png"],
  },
  { id: "m2015-8", y: 2015, num: 8,
    q: "光栅光谱的干涉级次 <span class=\"m\">m</span> 增大，则<span class=\"blank\"></span>。",
    o: ["自由光谱范围增大", "色散率增大", "分辨本领降低", "分辨本领不变"],
    a: 1,
  },
  { id: "m2015-9", y: 2015, num: 9,
    q: "与光栅刻线数 <span class=\"m\">N</span> 无关的量是<span class=\"blank\"></span>。",
    o: ["谱线的光强", "谱线的宽度", "谱线的位置", "谱线的分辨率"],
    a: 2,
  },
  { id: "m2015-10", y: 2015, num: 10,
    q: "衍射细丝测径仪是将单缝夫琅禾费衍射装置中的单缝替换为细丝，设所用光波波长为λ，透镜焦距为 <span class=\"m\">f</span>，今测得细丝产生的中央亮纹的宽度为 <span class=\"m\">l</span>，则细丝的宽度 <span class=\"m\">a</span> 为<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">a</span> = <span class=\"frac\"><span class=\"n\"><span class=\"m\">l</span></span><span class=\"d\"><span class=\"m\">f</span>λ</span></span>", "<span class=\"m\">a</span> = <span class=\"frac\"><span class=\"n\"><span class=\"m\">f</span>λ</span><span class=\"d\"><span class=\"m\">l</span></span></span>", "<span class=\"m\">a</span> = <span class=\"frac\"><span class=\"n\">2<span class=\"m\">f</span>λ</span><span class=\"d\"><span class=\"m\">l</span></span></span>", "<span class=\"m\">a</span> = <span class=\"frac\"><span class=\"n\"><span class=\"m\">l</span></span><span class=\"d\">2<span class=\"m\">f</span>λ</span></span>"],
    a: 2,
  },
  { id: "m2015-11", y: 2015, num: 11,
    q: "显微镜分辨率与下列因素中无关的是<span class=\"blank\"></span>。",
    o: ["照明光的波长", "数值孔径", "物镜的焦距", "目镜的口径"],
    a: 3,
  },
  { id: "m2015-12", y: 2015, num: 12,
    q: "如图所示，在夫琅禾费单缝衍射装置中，用波长为λ的平行光以角度φ斜入射到宽度为 <span class=\"m\">a</span> 的单缝，则零级衍射亮纹的半角宽度为<span class=\"blank\"></span>。",
    o: ["Δθ = <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\"><span class=\"m\">a</span></span></span>", "Δθ = <span class=\"frac\"><span class=\"n\">2λ</span><span class=\"d\"><span class=\"m\">a</span></span></span>", "Δθ = <span class=\"frac\"><span class=\"n\">2λ</span><span class=\"d\"><span class=\"m\">a</span>cosφ</span></span>", "Δθ = <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\"><span class=\"m\">a</span>cosφ</span></span>"],
    a: 3,
    fig: ["2015-12.png"],
  },
  { id: "m2015-13", y: 2015, num: 13,
    q: "圆偏振光通过半波片后，出射光为<span class=\"blank\"></span>。",
    o: ["与入射光旋转方向相同的圆偏振光", "线偏振光", "与入射光旋转方向相反的圆偏振光", "椭圆偏振光"],
    a: 2,
  },
  { id: "m2015-14", y: 2015, num: 14,
    q: "关于折射率椭球，下列说法不正确的是<span class=\"blank\"></span>。",
    o: ["折射率椭球完全由晶体的主介电常数确定。", "由折射率椭球通过几何作图可确定给定 <span class=\"m\">k</span><sub>0</sub> 的两个允许的特定线偏振光的 <span class=\"m\">D</span> 的方向。", "折射率椭球表征了对应任意线偏振光的 <span class=\"m\">D</span> 方向的折射率在空间的分布。", "折射率椭球表征了对应任意线偏振光的 <span class=\"m\">k</span><sub>0</sub> 方向的折射率在空间的分布。"],
    a: 3,
  },
  { id: "m2015-15", y: 2015, num: 15,
    q: "关于单轴晶体中的非常光，下列说法不正确的是<span class=\"blank\"></span>。",
    o: ["非常光总是不遵从折射定律。", "非常光的波矢量方向与能流方向一般不一致。", "非常光的相折射率的变化范围在 <span class=\"m\">n</span><sub>o</sub> 和 <span class=\"m\">n</span><sub>e</sub> 之间。", "非常光的电矢量方向在主平面内。"],
    a: 0,
  },
  { id: "m2015-16", y: 2015, num: 16,
    q: "下列琼斯矢量中，不表示右旋圆偏振光的是<span class=\"blank\"></span>。",
    o: ["<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">√<span class=\"rad\">2</span></span></span>[<span class=\"m\">1</span>; −<span class=\"m\">i</span>]", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">√<span class=\"rad\">2</span></span></span>[<span class=\"m\">1</span>; <span class=\"m\">i</span>]", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">√<span class=\"rad\">2</span></span></span>[<span class=\"m\">i</span>; <span class=\"m\">1</span>]", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">√<span class=\"rad\">2</span></span></span>[−<span class=\"m\">1</span>; <span class=\"m\">i</span>]"],
    a: 1,  note: "四个选项原卷都是 1/√2 乘以 2×1 列矢量，此处写成 [上行; 下行]。",
  },
  { id: "m2015-17", y: 2015, num: 17,
    q: "波片的功能是用于改变入射光的<span class=\"blank\"></span>。",
    o: ["波长", "频率", "偏振态", "强度"],
    a: 2,
  },
  { id: "m2015-18", y: 2015, num: 18,
    q: "光波的波矢 <span class=\"m\">k</span><sub>0</sub> 与单轴晶体光轴垂直传播时，其能流 <span class=\"m\">s</span><sub>0</sub> 的方向和 <span class=\"m\">k</span><sub>0</sub> 的方向<span class=\"blank\"></span>。",
    o: ["平行", "不确定", "离散角最大", "垂直"],
    a: 0,
  },
  { id: "m2015-19", y: 2015, num: 19,
    q: "描述光在介质中传播的色散特性的物理量是<span class=\"blank\"></span>。",
    o: ["复折射率", "复折射率的虚部", "复折射的实部", "复折射率的模"],
    a: 2,
  },
  { id: "m2015-20", y: 2015, num: 20,
    q: "线性散射和非线性散射的根本区别在于散射光和入射光的<span class=\"blank\"></span>不同。",
    o: ["光强", "频率", "相位", "偏振度"],
    a: 1,
  },
  { id: "m2016-1", y: 2016, num: 1,
    q: "对于频率为<span class=\"m\">ω</span>，初相位为<span class=\"m\">φ</span><sub>0</sub> 错误!未找到引用源。且沿 <span class=\"m\">z</span> 轴负方向传播的单色平面光波，其复数形式应表示为<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">E</span> = <span class=\"m\">E</span><sub>0</sub> exp[−<span class=\"m\">i</span>(<span class=\"m\">ω</span><span class=\"m\">t</span> − <span class=\"m\">k</span><span class=\"m\">z</span> + φ<sub>0</sub>)]", "<span class=\"m\">E</span> = <span class=\"m\">E</span><sub>0</sub> exp[−<span class=\"m\">i</span>(<span class=\"m\">ω</span><span class=\"m\">t</span> + <span class=\"m\">k</span><span class=\"m\">z</span> + φ<sub>0</sub>)]", "<span class=\"m\">E</span> = <span class=\"m\">E</span><sub>0</sub> exp[−<span class=\"m\">i</span>(<span class=\"m\">ω</span><span class=\"m\">t</span> − <span class=\"m\">k</span><span class=\"m\">z</span> − φ<sub>0</sub>)]", "<span class=\"m\">E</span> = <span class=\"m\">E</span><sub>0</sub> exp[−<span class=\"m\">i</span>(<span class=\"m\">ω</span><span class=\"m\">t</span> + <span class=\"m\">k</span><span class=\"m\">z</span> − φ<sub>0</sub>)]"],
    a: 1,  note: "题干里的「错误!未找到引用源。」是原卷自带的排版错误，照原卷保留。",
  },
  { id: "m2016-2", y: 2016, num: 2,
    q: "当单色平面光波在两种折射率不等的介质中振幅相等时，<span class=\"blank\"></span>。",
    o: ["其强度比等于两种介质的折射率之比", "其强度相等", "其强度比不确定", "其光频率不相等"],
    a: 0,
  },
  { id: "m2016-3", y: 2016, num: 3,
    q: "下述关于自然光的描述，不正确的为<span class=\"blank\"></span>。",
    o: ["自然光属于非偏振光", "自然光各个振动方向上振幅平均值相等", "两种自然光的混合依然为自然光", "自然光可以视为振幅相等、振动方向垂直且相位差恒定的两线偏振光的合成"],
    a: 3,
  },
  { id: "m2016-4", y: 2016, num: 4,
    q: "下述关于单色平面光波的描述，正确的是<span class=\"blank\"></span>。",
    o: ["单色平面光波的电矢量和磁矢量在同一平面", "自然界的光波通常可以表示为单色平面光波的叠加", "单色平面光波属于纵波", "持续时间有限的光波可能是单色平面光波"],
    a: 1,
  },
  { id: "m2016-5", y: 2016, num: 5,
    q: "一束右旋圆偏振光（迎着光传输方向看）以布儒斯特角从空气入射到玻璃界面时，它的反射光为<span class=\"blank\"></span>。",
    o: ["右旋圆偏振光（迎着光传输方向看）", "左旋圆偏振光（迎着光传输方向看）", "电矢量垂直于入射面的线偏振光", "电矢量平行于入射面的线偏振光"],
    a: 2,
  },
  { id: "m2016-6", y: 2016, num: 6,
    q: "一束线偏振光从光密介质射向光疏介质，下述描述正确的是<span class=\"blank\"></span>。",
    o: ["若正入射，则反射光为圆偏振光", "入射光的偏振方向和入射方向发生改变，折射光可能会发生相位突变", "若发生全反射，则反射光可能为椭圆偏振光", "若发生全反射，则衰逝波电场随离界面距离增加按线性规律衰减"],
    a: 2,
  },
  { id: "m2016-7", y: 2016, num: 7,
    q: "平行平板的等倾干涉图样定域在<span class=\"blank\"></span>。",
    o: ["无穷远", "平板上界面", "平板下界面", "自由空间"],
    a: 0,
  },
  { id: "m2016-8", y: 2016, num: 8,
    q: "在双缝干涉实验中，两条缝的宽度原来是相等的，若其中一缝的宽度略变窄，则<span class=\"blank\"></span>。",
    o: ["干涉条纹的间距变宽", "干涉条纹的间距变窄", "干涉条纹的间距不变，但原极小处的强度不再为零", "不再发生干涉现象"],
    a: 2,
  },
  { id: "m2016-9", y: 2016, num: 9,
    q: "F-P 腔两内腔面距离 <span class=\"m\">h</span> 增加时，其自由光谱范围 Δλ<span class=\"blank\"></span>。",
    o: ["恒定不变", "增加", "下降", "=0"],
    a: 2,
  },
  { id: "m2016-10", y: 2016, num: 10,
    q: "如图 a 所示，一光学平板玻璃 A 与待测工件 B 之间形成空气劈尖，用波长 λ=600nm 错误!未找到引用源。的单色光垂直照射，看到的反射光的干涉条纹如图 b 所示，有些条纹弯曲部分的顶点恰好与其右边条纹的直线部分的切线相切，则工件的上表面缺陷是<span class=\"blank\"></span>。",
    o: ["不平处为凸起纹，最大高度为 600nm", "不平处为凸起纹，最大高度为 300nm", "不平处为凹槽，最大深度为 600nm", "不平处为凹槽，最大深度为 300nm"],
    a: 1,  note: "题干里的「错误!未找到引用源。」是原卷自带的排版错误，照原卷保留。",
    fig: ["2016-10.png"],
  },
  { id: "m2016-11", y: 2016, num: 11,
    q: "把一平凸透镜放在平玻璃上，构成牛顿环装置，当平凸透镜慢慢地向上平移时，由反射光形成的牛顿环<span class=\"blank\"></span>。",
    o: ["向中心收缩，条纹间隔不变", "向中心收缩，环心呈明暗交替变化", "向外扩张，环心呈明暗交替变化", "向外扩张，条纹间隔变大"],
    a: 1,
  },
  { id: "m2016-12", y: 2016, num: 12,
    q: "在多缝夫琅禾费衍射中，其它条件不变，缝数增加时，衍射条纹会<span class=\"blank\"></span>。",
    o: ["变得宽而亮", "变得细而暗", "变得细而亮", "变得宽而暗"],
    a: 2,
  },
  { id: "m2016-13", y: 2016, num: 13,
    q: "在双缝衍射实验中，若双缝 S1 和 S2 的中心之间的距离 <span class=\"m\">d</span> 稍微减小，且把两条缝的宽度 <span class=\"m\">a</span> 略微加宽，则<span class=\"blank\"></span>。",
    o: ["中央明纹变宽，其中所包含的干涉条纹数目变少", "中央明纹变宽，其中所包含的干涉条纹数目变多", "中央明纹变窄，其中所包含的干涉条纹数目变少", "中央明纹变窄，其中所包含的干涉条纹数目变多"],
    a: 2,
  },
  { id: "m2016-14", y: 2016, num: 14,
    q: "波长 λ = 800nm 的单色平行光垂直入射到一块透光缝宽为 <span class=\"m\">a</span> = 0.002mm 的衍射光栅上，发现有两个相邻的主极大分别出现在 sinθ = 0.2 错误!未找到引用源。和 sinθ = 0.3 错误!未找到引用源。的方向上，则第<span class=\"blank\"></span>级次缺级。",
    o: ["3", "4", "5", "6"],
    a: 1,  note: "题干里的「错误!未找到引用源。」是原卷自带的排版错误，照原卷保留。",
  },
  { id: "m2016-15", y: 2016, num: 15,
    q: "设瞳孔直径为 3mm，且人眼明视距离为 25cm。对波长为 600nm 的光而言，人能分辨两点的极限距离为<span class=\"blank\"></span>。",
    o: ["0.0244mm", "0.061cm", "0.061mm", "0.0244cm"],
    a: 2,
  },
  { id: "m2016-16", y: 2016, num: 16,
    q: "一个波带片的孔径内有 10 个半波带，让其中的 5 个奇数带通光，5 个偶数带被挡住，则中心轴上相应的衍射场点的光强为自由传播时光强的<span class=\"blank\"></span>倍。",
    o: ["5", "10", "50", "100"],
    a: 3,
  },
  { id: "m2016-17", y: 2016, num: 17,
    q: "关于光在单轴晶体中的传输，正确的说法是<span class=\"blank\"></span>。",
    o: ["当波矢沿着光轴方向时，<span class=\"m\">o</span> 光和 <span class=\"m\">e</span> 光的光线方向不同", "当波矢沿着垂直于光轴方向时，离散角最大", "当波矢沿着垂直于光轴方向时，<span class=\"m\">o</span> 光和 <span class=\"m\">e</span> 光的折射率差最小", "当波矢不沿着光轴且也不垂直于光轴方向时，不一定存在两条光线"],
    a: 3,
  },
  { id: "m2016-18", y: 2016, num: 18,
    q: "关于折射率椭球，正确的说法是<span class=\"blank\"></span>。",
    o: ["矢量的大小表示 <span class=\"m\">D</span>⃗ 沿着矢量方向的线偏振光的折射率", "矢量的大小表示 <span class=\"m\">E</span>⃗ 沿着矢量方向的线偏振光的折射率", "矢量的大小表示 <span class=\"m\">k</span>⃗ 沿着矢量方向的线偏振光的折射率", "矢量的大小表示 <span class=\"m\">s</span>⃗ 沿着矢量方向的线偏振光的折射率"],
    a: 0,
  },
  { id: "m2016-19", y: 2016, num: 19,
    q: "能用于鉴别左旋圆偏振光和右旋圆偏振光的器件（或器件组合）是<span class=\"blank\"></span>。",
    o: ["偏振片，补偿器", "偏振片，1/2 波片", "1/2 波片，1/4 波片", "偏振片，1/4 波片"],
    a: 3,
  },
  { id: "m2016-20", y: 2016, num: 20,
    q: "如图所示，当偏振片 P 旋转一周时，出射光强 <span class=\"m\">I</span> 随之变化，但是整个过程无消光现象，则入射光是<span class=\"blank\"></span>。",
    o: ["部分偏振光", "椭圆偏振光", "圆偏振光", "部分偏振光或椭圆偏振光"],
    a: 3,
    fig: ["2016-20.png"],
  },
  { id: "m2016-21", y: 2016, num: 21,
    q: "使一强度为 <span class=\"m\">I</span><sub>0</sub> 的平面偏振光先后通过两个偏振片 P<sub>1</sub> 和 P<sub>2</sub>，如果 P<sub>1</sub> 和 P<sub>2</sub> 的偏振化方向与原入射光电矢量振动方向的夹角分别是 <span class=\"m\">α</span> 和 90 度，则通过这两个偏振片后的光强度 <span class=\"m\">I</span> 是<span class=\"blank\"></span>。",
    o: ["<span class=\"frac\"><span class=\"n\"><span class=\"m\">I</span><sub>0</sub></span><span class=\"d\">2</span></span>cos<sup>2</sup><span class=\"m\">α</span>", "0", "<span class=\"frac\"><span class=\"n\"><span class=\"m\">I</span><sub>0</sub></span><span class=\"d\">4</span></span>sin<sup>2</sup>(2<span class=\"m\">α</span>)", "<span class=\"frac\"><span class=\"n\"><span class=\"m\">I</span><sub>0</sub></span><span class=\"d\">4</span></span>sin<sup>2</sup><span class=\"m\">α</span>"],
    a: 2,
  },
  { id: "m2016-22", y: 2016, num: 22,
    q: "关于自然旋光现象的描述，正确的说法为<span class=\"blank\"></span>。",
    o: ["旋光物质和半波片都能使线偏振光的偏振方向旋转一定角度，属于同一种光学现象", "对于右旋晶体，右旋圆偏振光的折射率比左旋圆偏振光的折射率小", "不同波长的线偏振可见光通过同一旋光物质，长波长光偏振方向转过的角度最大", "线偏振光正向和反向通过右旋晶体，沿着光传播的方向观察时，偏振方向始终沿顺时针方向旋转"],
    a: 1,
  },
  { id: "m2016-23", y: 2016, num: 23,
    q: "下述散射方式中，入射光与散射光波长不同的是<span class=\"blank\"></span>。",
    o: ["瑞利散射", "分子散射", "米氏散射", "拉曼散射"],
    a: 3,
  },
  { id: "m2016-24", y: 2016, num: 24,
    q: "黄金呈现黄色，主要是因为<span class=\"blank\"></span>。",
    o: ["选择吸收", "一般吸收", "瑞利散射", "共振吸收"],
    a: 0,
  },
  { id: "m2016-25", y: 2016, num: 25,
    q: "关于反常色散，描述正确的是<span class=\"blank\"></span>。",
    o: ["在反常色散区，光波传播速度与波长成正比", "在反常色散区，入射光频率远离分子的固有振动频率", "在反常色散区，准单色波的相速度等于群速度", "在反常色散区，介质折射率随波长增加而增加"],
    a: 3,
  },
  { id: "m2017-1", y: 2017, num: 1,
    q: "自然光在界面发生反射和折射，当反射光为线偏振光时，折射光与反射光的夹角必为（ ）",
    o: ["<span class=\"m\">θ</span><sub>B</sub>", "<span class=\"m\">θ</span><sub>C</sub>", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">3</span></span>", "<span class=\"frac\"><span class=\"n\">π</span><span class=\"d\">2</span></span>"],
    a: 3,  note: "第 1 章",
  },
  { id: "m2017-2", y: 2017, num: 2,
    q: "全反射时，在折射率小的介质中的电场（ ）。",
    o: ["等于零", "随离界面距离的增加按指数规律衰减", "等于常数", "随离界面距离的增加按指数规律增加"],
    a: 1,  note: "第 1 章",
  },
  { id: "m2017-3", y: 2017, num: 3,
    q: "当光波在两种不同介质中的振幅相等时，（ ）",
    o: ["其强度相等", "其强度不相等", "不确定", "其强度比等于两种介质的折射率之比"],
    a: 3,  note: "第 1 章",
  },
  { id: "m2017-4", y: 2017, num: 4,
    q: "同一介质中，圆偏振光的电场为 <span class=\"m\">E</span>，线偏振光的电场振幅为 <span class=\"m\">E</span>，两光的光强之间的关系为（ ）",
    o: ["<span class=\"m\">I</span><sub>圆</sub>=<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub>=2<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub><<span class=\"m\">I</span><sub>线</sub>", "<span class=\"m\">I</span><sub>圆</sub>=√2<span class=\"m\">I</span><sub>线</sub>"],
    a: 1,  note: "第 1 章。卷面「圆偏振光的电场为 E」处 E 后没有下标。",
  },
  { id: "m2017-5", y: 2017, num: 5,
    q: "在白光入射的等倾干涉中，同级圆环中相应于颜色紫到红的空间位置是（ ）。",
    o: ["由外到里", "由里到外", "不变", "随机变化"],
    a: 0,  note: "第 2 章",
  },
  { id: "m2017-6", y: 2017, num: 6,
    q: "把一平凸透镜放在平玻璃上构成牛顿环装置，当平凸透镜慢慢地向上平移时，由反射光形成的牛顿环（ ）。",
    o: ["向中心收缩，条纹间隔不变", "向中心收缩，环心呈明暗交替变化", "向外扩张，环心呈明暗交替变化", "向外扩张，条纹间隔变大"],
    a: 1,  note: "第 2 章",
  },
  { id: "m2017-7", y: 2017, num: 7,
    q: "等倾干涉条纹和牛顿环都是明暗相间的同心圆环，（ ）。",
    o: ["两者都是中心部分圆环的干涉级次大", "两者都是边缘部分圆环的干涉级次大", "前者中心部分圆环的干涉级次大，后者边缘部分圆环的干涉级次大", "前者边缘部分圆环的干涉级次大，后者中心部分圆环的干涉级次大"],
    a: 2,  note: "第 2 章",
  },
  { id: "m2017-8", y: 2017, num: 8,
    q: "对于单层光学薄膜，增透膜和增反膜的光学厚度（ ）",
    o: ["分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "分别为 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span> 和 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">4</span></span>", "都等于 <span class=\"frac\"><span class=\"n\">λ</span><span class=\"d\">2</span></span>"],
    a: 2,  note: "第 2 章",
  },
  { id: "m2017-9", y: 2017, num: 9,
    q: "F-P 腔两平行腔面间的距离增加时，其（ ）。",
    o: ["分辨能力增强", "分辨能力降低", "自由光谱范围增大", "最小可分辨波长差增大"],
    a: 0,  note: "第 2 章",
  },
  { id: "m2017-10", y: 2017, num: 10,
    q: "在 F-P 腔腔面无吸收的情况下，当反射率 <span class=\"m\">R</span> 增加时，其干涉图样中亮线的亮度（ ）",
    o: ["增加", "减弱", "不变", "趋于无穷大"],
    a: 2,  note: "第 2 章",
  },
  { id: "m2017-11", y: 2017, num: 11,
    q: "15. 关于光的空间相干性，下列说法不正确的是（ ）。",
    o: ["光场的空间相干性来源于普通扩展光源不同部分发出的光的不相干性", "普通光源的空间扩展越大，其光场的空间相干范围越小", "光的空间相干性反映了光波场的横向相干性", "空间相干性与光波的波列长度有关"],
    a: 3,  note: "第 2 章。卷面题干前多印了「15.」。",
  },
  { id: "m2017-12", y: 2017, num: 12,
    q: "关于光的时间相干性，下列说法不正确的是（ ）。",
    o: ["光场的时间相干性来源于普通光源的原子发光持续时间的有限性", "光场的时间相干性与光源的光谱展宽无关", "光场的时间相干性反映了光场的纵向相干性", "光波的波列越长，其光场的时间相干性越好"],
    a: 1,  note: "第 2 章",
  },
  { id: "m2017-13", y: 2017, num: 13,
    q: "夫朗和费衍射图样是一簇椭圆，长轴在 <span class=\"m\">y</span> 轴方向，衍射屏的通光孔为（ ）",
    o: ["圆", "窄缝", "椭圆，长轴在 <span class=\"m\">x</span> 方向", "椭圆，长轴在 <span class=\"m\">y</span> 方向"],
    a: 2,  note: "第 3 章",
  },
  { id: "m2017-14", y: 2017, num: 14,
    q: "使夫琅和费矩孔衍射装置中的矩孔在其自身面内平移，则衍射图样（ ）。",
    o: ["不变", "同向平移", "反向平移", "旋转"],
    a: 0,  note: "第 3 章",
  },
  { id: "m2017-15", y: 2017, num: 15,
    q: "在单缝夫琅和费衍射实验中，波长为 λ 的单色光垂直入射在宽度为 <span class=\"m\">a</span>=4λ 的单缝上，对应于衍射角为 30 的方向，单缝处波阵面可分成的半波带数目为（ ）。",
    o: ["2个", "4个", "6个", "8个"],
    a: 1,  note: "第 3 章。卷面「30」后无度号。",
  },
  { id: "m2017-16", y: 2017, num: 16,
    q: "多缝夫琅和费衍射中，其它条件不变，缝数增加时，衍射条纹（ ）。",
    o: ["变亮", "变暗", "亮度不变", "变宽"],
    a: 0,  note: "第 3 章",
  },
  { id: "m2017-17", y: 2017, num: 17,
    q: "在均匀平面波垂直入射的夫琅和费多缝衍射中，相邻缝在观察屏上同一点的衍射场（ ）",
    o: ["振幅、相位都相同", "振幅、相位都不相同", "振幅相同、相位不相同", "振幅不相同、相位相同"],
    a: 2,  note: "第 3 章",
  },
  { id: "m2017-18", y: 2017, num: 18,
    q: "地球与月球相距 3.8×10<sup>5</sup> km，用口径为 1m 的天文望远镜（取光波长 = 550 nm）能分辨月球表面两点的最小距离约为（ ）。",
    o: ["96 m", "128 m", "255 m", "510 m"],
    a: 2,  note: "第 3 章。卷面「取光波长」与「=」之间空缺一个符号（疑为 λ），且「3.8×105」的 105 排版为 10<sup>5</sup>。",
  },
  { id: "m2017-19", y: 2017, num: 19,
    q: "闪耀光栅主闪耀波长为 12，对它不呈现闪耀的波长是（ ）",
    o: ["2", "3", "5", "6"],
    a: 2,  note: "第 3 章。卷面「12」后空缺单位（疑为 μm）。",
  },
  { id: "m2017-20", y: 2017, num: 20,
    q: "如下图所示，由入缝 A 进入的白光经光栅衍射分光后由出缝 B 射出。现保持入缝、出缝的位置不变，使光栅绕 C 轴按顺时针方向旋转时，同级衍射光由出缝 B 射出的光（ ）。",
    o: ["呈紫色", "呈红色", "由紫转红", "由红转紫"],
    a: 2,  note: "第 3 章。题面插图在下一页页首。",
    fig: ["2017-20.png"],
  },
  { id: "m2017-21", y: 2017, num: 21,
    q: "一个波带片的孔径内有 10 个半波带，让其中的 5 个奇数带通光，5 个偶数带被挡住，则中心轴上相应衍射场点的光强为自由传播时此处光强的（ ）倍。",
    o: ["5", "10", "20", "100"],
    a: 3,  note: "第 3 章",
  },
  { id: "m2017-22", y: 2017, num: 22,
    q: "费涅耳圆屏衍射中，如果圆屏直径有限大，则其中垂线上考察点（ ）。",
    o: ["总呈暗斑", "总呈亮斑", "可亮也可能暗", "时暗时亮"],
    a: 1,  note: "第 3 章",
  },
  { id: "m2017-23", y: 2017, num: 23,
    q: "在各向异性晶体中，<span class=\"m\">E</span>、<span class=\"m\">D</span> 的方向（ ）",
    o: ["一定不同", "一定相同", "互相垂直", "不一定相同"],
    a: 3,  note: "第 4 章",
  },
  { id: "m2017-24", y: 2017, num: 24,
    q: "以 <span class=\"m\">k⃗</span>、<span class=\"m\">s⃗</span> 分别表示光波的波矢和波印廷矢量，在各向异性晶体中，（ ）",
    o: ["<span class=\"m\">k⃗</span> 平行于 <span class=\"m\">s⃗</span>", "<span class=\"m\">k⃗</span> 垂直于 <span class=\"m\">s⃗</span>", "<span class=\"m\">k⃗</span>、<span class=\"m\">s⃗</span> 都垂直于 <span class=\"m\">H⃗</span>", "<span class=\"m\">k⃗</span>、<span class=\"m\">s⃗</span> 都垂直于 <span class=\"m\">E⃗</span>"],
    a: 2,  note: "第 4 章。原题 k、s、H、E 均带矢量箭头，此处用 ⃗ 表示。",
  },
  { id: "m2017-25", y: 2017, num: 25,
    q: "应用波片时，波矢传播方向一般（D）",
    o: ["平行于快轴", "平行于慢轴", "平行于快、慢轴", "垂直于快、慢轴"],
    a: 3,  note: "第 4 章。卷面括号内已印成「D」（疑为答案误入题面）。",
  },
  { id: "m2017-26", y: 2017, num: 26,
    q: "强度为 <span class=\"m\">I</span><sub>i</sub> 的部分偏振光由一束自然光和一束圆偏振光组成，其强度分别为 <span class=\"m\">I</span><sub>N</sub> 和 <span class=\"m\">I</span><sub>C</sub>。让该光束依次通过 1/4 波片和检偏器，旋转检偏器，发现得到的最小光强为 <span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">4</span></span><span class=\"m\">I</span><sub>i</sub>，可以断定（ ）",
    o: ["<span class=\"m\">I</span><sub>N</sub> = <span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub> > <span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub> < <span class=\"m\">I</span><sub>C</sub>", "<span class=\"m\">I</span><sub>N</sub> = 2<span class=\"m\">I</span><sub>C</sub>"],
    a: 0,  note: "第 4 章",
  },
  { id: "m2017-27", y: 2017, num: 27,
    q: "12. 线偏振光通过半波片后，一定是（ ）",
    o: ["圆偏振光", "线偏振光", "椭圆偏振光", "自然光"],
    a: 1,  note: "第 4 章。卷面题干前多印了「12.」。",
  },
  { id: "m2017-28", y: 2017, num: 28,
    q: "使一光强为 <span class=\"m\">I</span><sub>0</sub> 的平面偏振光先后通过两个偏振片 <span class=\"m\">P</span><sub>1</sub> 和 <span class=\"m\">P</span><sub>2</sub>，如果 <span class=\"m\">P</span><sub>1</sub> 和 <span class=\"m\">P</span><sub>2</sub> 的偏振化方向与原入射光光矢量振动方向的夹角分别是 α 和 90°，则通过这两个偏振片后的光的强度 <span class=\"m\">I</span> 是（ ）",
    o: ["<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">2</span></span><span class=\"m\">I</span><sub>0</sub>cos<sup>2</sup>α", "0", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">4</span></span><span class=\"m\">I</span><sub>0</sub>sin<sup>2</sup>(2α)", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">4</span></span><span class=\"m\">I</span><sub>0</sub>sin<sup>2</sup>α"],
    a: 2,  note: "第 4 章",
  },
  { id: "m2017-29", y: 2017, num: 29,
    q: "一束圆偏振光通过 1/4 波片后为（ ）",
    o: ["圆偏振光", "线偏振光", "椭圆偏振光", "自然光"],
    a: 1,  note: "第 4 章",
  },
  { id: "m2017-30", y: 2017, num: 30,
    q: "一束光强为 <span class=\"m\">I</span><sub>0</sub> 的自然光依次通过两个偏振片 <span class=\"m\">P</span><sub>1</sub> 和 <span class=\"m\">P</span><sub>2</sub>，若 <span class=\"m\">P</span><sub>1</sub> 和 <span class=\"m\">P</span><sub>2</sub> 的偏振化方向的夹角为 30°，则透射偏振光的光强是（ ）",
    o: ["<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">4</span></span><span class=\"m\">I</span><sub>0</sub>", "<span class=\"frac\"><span class=\"n\">√3</span><span class=\"d\">4</span></span><span class=\"m\">I</span><sub>0</sub>", "<span class=\"frac\"><span class=\"n\">1</span><span class=\"d\">8</span></span><span class=\"m\">I</span><sub>0</sub>", "<span class=\"frac\"><span class=\"n\">3</span><span class=\"d\">8</span></span><span class=\"m\">I</span><sub>0</sub>"],
    a: 3,  note: "第 4 章",
  },
  { id: "m2017-31", y: 2017, num: 31,
    q: "相对于入射光，散射光频率发生变化的散射是：（ ）",
    o: ["拉曼散射", "米氏散射", "线性散射", "瑞利散射"],
    a: 0,  note: "第 5 章",
  },
  { id: "m2017-32", y: 2017, num: 32,
    q: "牛奶在自然光照射下呈白色，则牛奶对光的散射主要为（ ）",
    o: ["瑞利散射", "分子散射", "米氏散射", "拉曼散射"],
    a: 2,  note: "第 5 章",
  },
  { id: "m2017-33", y: 2017, num: 33,
    q: "普通玻璃对日光的吸收属于（ ）",
    o: ["选择吸收", "一般吸收", "强烈吸收", "双光子吸收"],
    a: 1,  note: "第 5 章",
  },
  { id: "m2022-1", y: 2022, num: 1,
    q: "尼科尔棱镜主截面从 30° 变为 45°，光强变为原来的<span class=\"blank\"></span>。",
    o: ["不变", "2/3", "1/2"],
    a: 1,  note: "卷面本题只有 3 个选项（A、B、C）。",
  },
  { id: "m2022-2", y: 2022, num: 2,
    q: "透镜置于标准球面检测，人在观测时，埋头看去发现条纹收缩<span class=\"blank\"></span>",
    o: ["打磨两侧", "打磨中间", "全部打磨", "不变化"],
    a: 0,  note: "「埋头看去」是原卷原文（回忆版），未改。",
  },
  { id: "m2022-3", y: 2022, num: 3,
    q: "膜 n=1.3（上方为 n=1，下方为玻璃 n=1.5），反射光干涉相消（λ=550nm），问膜厚<span class=\"blank\"></span>？",
    o: ["110nm", "105.8nm", "130nm", "150nm"],
    a: 1,  note: "原卷本题是一幅分层示意图（上层 n=1、中间膜 n=1.3、下层玻璃 n=1.5），此处把三层标注写进了题干，免得丢信息。",
  },
  { id: "m2022-4", y: 2022, num: 4,
    q: "关于磁致旋光介质，以下说法错误的是<span class=\"blank\"></span>。",
    o: ["偏转角度与介质长度和磁场强度成正比", "偏转方向与磁场 B 有关，与光的入射方向无关", "磁光不能作为光强度调制"],
    a: 2,  note: "卷面本题只有 3 个选项（A、B、C）。第 3 个选项原文即「磁光不能作为光强度调制」（句末没有「器」字，也没有句号），照实录。",
  },
  { id: "m2022-5", y: 2022, num: 5,
    q: "光栅只能看到零级和一级，则应该<span class=\"blank\"></span>增大级次。",
    o: ["光栅靠近透镜", "光栅远离透镜", "增大光栅常数"],
    a: 2,  note: "卷面本题只有 3 个选项（A、B、C），其中 C 项跨页排在下一页首行。",
  },
  { id: "m2022-6", y: 2022, num: 6,
    q: "与肥皂泡法线成 30° 角观察肥皂泡，n 为 1.3，观察到绿光 550nm，现在以法线角度观察，是<span class=\"blank\"></span>颜色。",
    o: ["白色", "黄色", "绿色", "紫色"],
    a: 1,
  },
  { id: "m2022-8", y: 2022, num: 8,
    q: "在杨氏双缝干涉实验中，将双缝板旋转 θ 角，由竖直变成倾斜（逆时针转），中心亮纹会<span class=\"blank\"></span>",
    o: ["消失", "向上移", "向下移", "不变"],
    a: 3,  note: "题面另附双缝干涉示意图。",
    fig: ["2022-8.png"],
  },
  { id: "m2022-9", y: 2022, num: 9,
    q: "<span class=\"blank\"></span>是非线性散射。",
    o: ["瑞利散射", "拉曼散射", "米氏散射", "烟雾散射"],
    a: 1,
  },
  { id: "m2023-1", y: 2023, num: 1,
    q: "两束强度相等，振动方向垂直，相位差为 π/2 的线偏振光叠加，形成的光为<span class=\"blank\"></span>。",
    o: ["线偏振光", "部分偏振光", "圆偏振光", "椭圆偏振光"],
    a: 2,
  },
  { id: "m2023-2", y: 2023, num: 2,
    q: "一椭圆偏振光通过一偏振片，转动偏振片一周，最大光强为 3<span class=\"m\">I</span><sub>0</sub>，最小光强为 <span class=\"m\">I</span><sub>0</sub>，现在把偏振片的透光轴相对于最大光强方向顺时针转动 45°，此时的出射光强为<span class=\"blank\"></span>",
    o: ["1.33<span class=\"m\">I</span><sub>0</sub>", "1.44<span class=\"m\">I</span><sub>0</sub>", "1.67<span class=\"m\">I</span><sub>0</sub>", "2<span class=\"m\">I</span><sub>0</sub>"],
    a: 3,
  },
  { id: "m2023-3", y: 2023, num: 3,
    q: "自然光正入射界面，反射光为<span class=\"blank\"></span>；以布儒斯特角入射界面，反射光为<span class=\"blank\"></span>。",
    o: ["线偏振光；部分偏振光", "自然光；线偏振光", "部分偏振光；线偏振光", "线偏振光；自然光"],
    a: 1,  note: "双空题：两个空共用一组选项，选项里用「；」分开两空的答案。",
  },
  { id: "m2023-4", y: 2023, num: 4,
    q: "光在光密-光疏界面发生全反射，则（题目存疑）<span class=\"blank\"></span>",
    o: ["光密界面有电磁波", "光疏界面有倏逝波", "光疏界面有电磁波", "光密界面有倏逝波"],
    a: 1,  note: "原卷题面自带「（题目存疑）」标注。",
  },
  { id: "m2023-5", y: 2023, num: 5,
    q: "下列哪项不是光的相干条件<span class=\"blank\"></span>",
    o: ["同一粒子发出的光", "传播方向相同", "光程差不能太大", "粒子同一时刻发出的光"],
    a: 1,
  },
  { id: "m2023-6", y: 2023, num: 6,
    q: "关于 F-P 干涉仪与衍射光栅的分辨本领，下列说法正确的是<span class=\"blank\"></span>",
    o: ["都是提高干涉级次来提高分辨本领", "前者提高干涉级次来提高分辨本领，后者提高衍射级次", "前者靠提高干涉级次，后者靠提高缝数", "都是靠提高反射率来提高"],
    a: 2,
  },
  { id: "m2023-7", y: 2023, num: 7,
    q: "两个理想点光源在三维自由空间的干涉属于<span class=\"blank\"></span>",
    o: ["非定域干涉", "定域的等厚干涉", "非定域的等倾干涉", "定域或非定域，等厚或等倾都有可能"],
    a: 0,
  },
  { id: "m2023-8", y: 2023, num: 8,
    q: "由杨氏双缝干涉提出的“干涉孔径角”属于<span class=\"blank\"></span>概念。",
    o: ["空间相干性", "时间相干性"],
    a: 0,  note: "原卷（回忆版）只印出 A、B 两个选项，缺 C、D。",
  },
  { id: "m2023-9", y: 2023, num: 9,
    q: "关于菲涅尔衍射与夫琅禾费衍射说法正确的是<span class=\"blank\"></span>。",
    o: ["菲涅尔衍射是傅里叶变换", "夫琅禾费衍射是傅里叶变换", "两者都是傅里叶变换", "两者都不是傅里叶变换"],
    a: 1,
  },
  { id: "m2023-10", y: 2023, num: 10,
    q: "一块波带片有 8 个半波带，4 个奇数带通光，4 个偶数带被挡位，则其光强为自由传播时的<span class=\"blank\"></span>倍",
    o: ["64", "48", "32", "16"],
    a: 0,  note: "「被挡位」是原卷印刷文字，未改。",
  },
  { id: "m2023-11", y: 2023, num: 11,
    q: "两正交偏振片插入第二偏振片，自然光通过，出射光强可能为<span class=\"blank\"></span>。",
    o: ["<span class=\"m\">I</span>", "<span class=\"m\">I</span>/2", "<span class=\"m\">I</span>/4", "<span class=\"m\">I</span>/8"],
    a: 3,
  },
  { id: "m2023-14", y: 2023, num: 14,
    q: "光栅刻痕密度不变，入射光波长不变，入射光束与光栅的相对方向不变，且全投射再光栅面内，如果光束横截面面积减小，光栅的分辨能力会<span class=\"blank\"></span>。",
    o: ["降低", "升高", "=0", "不变"],
    a: 0,  note: "「全投射再光栅面内」是原卷印刷文字（应为「在」），未改。",
  },
  { id: "m2023-16", y: 2023, num: 16,
    q: "可以使右旋圆偏光强度减半变左旋的器件是<span class=\"blank\"></span>。",
    o: ["偏振片，1/4 波片", "偏振片，半波片", "1/4 波片", "1/2 波片"],
    a: 3,
  },
  { id: "m2023-17", y: 2023, num: 17,
    q: "复折射率中表示吸收特性的部分是<span class=\"blank\"></span>。",
    o: ["复折射率", "复折射率的虚部", "复折射率的实部", "复折射率的模"],
    a: 1,
  },
  { id: "m2023-19", y: 2023, num: 19,
    q: "瑞利散射和布里渊散射的本质区别是<span class=\"blank\"></span>。",
    o: ["波长", "光强", "散射角"],
    a: 0,  note: "原卷（回忆版）只印出 A、B、C 三个选项，缺 D。",
  },
  { id: "m2023-20", y: 2023, num: 20,
    q: "拉曼散射会产生新的频率分量，其与入射光的频率差的主要影响因素为<span class=\"blank\"></span>",
    o: ["散射介质", "观察角度", "入射光波长", "入射光频率"],
    a: 0,
  },
  { id: "m2023-21", y: 2023, num: 21,
    q: "为什么会有彩虹<span class=\"blank\"></span>",
    o: ["神秘自然现象", "光的衍射", "空气对光产生的米氏散射", "水滴对光的折射"],
    a: 3,
  },
];
